/**
 * Runtime resolver for the component registry.
 *
 * Consumers — pages, the showcase, AI agents — call these helpers instead of
 * importing the raw index. The Index is generated by `scripts/build-registry.ts`
 * from the `_registry.ts` files under `src/components/{ui,examples,blocks}/`.
 */
import type { ComponentType } from "react";
import { Index, ItemsByArea, ExamplesBySlug } from "@/components/__index__";
import type { RegistryItem } from "@/lib/registry-schema";

export function getRegistryItem(name: string): RegistryItem | undefined {
  return Index[name]?.meta;
}

export function getRegistryComponent(name: string): ComponentType | undefined {
  return Index[name]?.Component;
}

export function getExamplesForSlug(slug: string): RegistryItem[] {
  const names = ExamplesBySlug[slug] ?? [];
  return names.map((n) => Index[n]?.meta).filter((m): m is RegistryItem => Boolean(m));
}

export function listUiSlugs(): string[] {
  return ItemsByArea.ui;
}

export function listExampleNames(): string[] {
  return ItemsByArea.examples;
}

export function listBlockNames(): string[] {
  return ItemsByArea.blocks;
}

export function listAllItems(): RegistryItem[] {
  return Object.values(Index).map((e) => e.meta);
}

/**
 * Find items whose name, title, description, or categories match the query.
 * Used by AI agents to discover what's already in the library before authoring
 * new variants.
 */
export function searchRegistry(query: string): RegistryItem[] {
  const q = query.toLowerCase();
  return listAllItems().filter((item) => {
    const haystack = [
      item.name,
      item.title ?? "",
      item.description ?? "",
      ...(item.categories ?? []),
      ...(item.related ?? []),
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(q);
  });
}
