export type Locale = "en" | "cs";

export const dict: Record<Locale, Record<string, string>> = {
  en: {
    meta_title: "Sign in · LAC",
    alert_title: "Scheduled maintenance",
    alert_desc: "Sign-in resumes 5 May 2026 at 20:00 CET. Existing sessions are unaffected.",
    view_details: "View details",
    form_title: "Welcome back",
    form_subtitle: "Sign in to your LAC workspace.",
    email_label: "Work email",
    email_placeholder: "name@company.com",
    password_label: "Password",
    forgot_password: "Forgot password?",
    login: "Sign in",
    or: "or",
    login_magic_link: "Continue with magic link",
    sign_in_passkey: "Continue with passkey",
    sign_in_sso: "Continue with SSO",
    dialog_title: "Sign-in is temporarily unavailable",
    dialog_desc:
      "We are upgrading core infrastructure. Sign-in resumes automatically at the end of the maintenance window.",
    dialog_window: "Maintenance window",
    dialog_continue: "Got it",
    right_headline: "Faster, bigger, ready for what you build next.",
    right_desc:
      "We are upgrading the platform during the window below. No data or settings change.",
    card_compute: "Compute",
    card_storage: "Storage",
    card_speed: "Response time",
    card_speed_value: "62% faster",
    ai_kicker: "Shipping with this release",
    ai_title: "AI Assistant, redesigned",
    ai_desc: "Context-aware suggestions, inline actions, and faster answers across your workspace.",
    footer_copyright: "© 2026 afframe s.r.o.",
    footer_compliance: "SOC 2 · GDPR · ISO 27001",
    footer_status: "status.afframe.com",
    footer_privacy: "Privacy",
    footer_terms: "Terms",
  },
  cs: {
    meta_title: "Přihlášení · LAC",
    alert_title: "Plánovaná údržba",
    alert_desc:
      "Přihlášení bude obnoveno 5. května 2026 ve 20:00 SEČ. Aktivní relace zůstávají nedotčeny.",
    view_details: "Zobrazit podrobnosti",
    form_title: "Vítejte zpět",
    form_subtitle: "Přihlaste se do svého pracovního prostoru LAC.",
    email_label: "Pracovní e-mail",
    email_placeholder: "jmeno@firma.cz",
    password_label: "Heslo",
    forgot_password: "Zapomněli jste heslo?",
    login: "Přihlásit se",
    or: "nebo",
    login_magic_link: "Pokračovat pomocí magic linku",
    sign_in_passkey: "Pokračovat pomocí passkey",
    sign_in_sso: "Pokračovat přes SSO",
    dialog_title: "Přihlášení je dočasně nedostupné",
    dialog_desc:
      "Provádíme upgrade klíčové infrastruktury. Přihlášení bude obnoveno automaticky po skončení okna údržby.",
    dialog_window: "Okno údržby",
    dialog_continue: "Rozumím",
    right_headline: "Rychlejší, větší, připravené na to, co stavíte dál.",
    right_desc: "Platformu vylepšujeme během okna níže. Vaše data ani nastavení se nemění.",
    card_compute: "Výpočetní výkon",
    card_storage: "Úložiště",
    card_speed: "Doba odezvy",
    card_speed_value: "o 62 % rychleji",
    ai_kicker: "Součástí tohoto vydání",
    ai_title: "Přepracovaný AI asistent",
    ai_desc: "Kontextové návrhy, inline akce a rychlejší odpovědi v celém pracovním prostoru.",
    footer_copyright: "© 2026 afframe s.r.o.",
    footer_compliance: "SOC 2 · GDPR · ISO 27001",
    footer_status: "status.afframe.com",
    footer_privacy: "Soukromí",
    footer_terms: "Podmínky",
  },
};
