/**
 * Reads every `_registry.ts` under `src/components/{ui,examples,blocks}/` and
 * emits `src/components/__index__.tsx` — the runtime index used by
 * `<ComponentPreview>` and consumers.
 *
 * Output shape mirrors shadcn's `apps/v4/registry/__index__.tsx`:
 * a single `Index` object keyed by item name, with a literal
 * `React.lazy(() => import("@/components/<area>/<name>"))` per entry so the
 * bundler can resolve chunks statically.
 *
 * Run: `pnpm registry:build`
 * Pre-commit hook + CI run this and fail on `git diff` against the result.
 */
import * as fs from "node:fs";
import * as path from "node:path";

import { items as uiItems } from "../src/components/ui/_registry";
import { items as exampleItems } from "../src/components/examples/_registry";
import { items as blockItems } from "../src/components/blocks/_registry";
import type { RegistryItem } from "../src/lib/registry-schema";

const REPO_ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.join(REPO_ROOT, "src/components/__index__.tsx");

type Area = "ui" | "examples" | "blocks";

function areaFor(item: RegistryItem): Area {
  switch (item.type) {
    case "registry:ui":
      return "ui";
    case "registry:example":
      return "examples";
    case "registry:block":
      return "blocks";
    default:
      throw new Error(`Unsupported type for registry index: ${item.type}`);
  }
}

function validate(items: RegistryItem[]): void {
  const seen = new Set<string>();
  const allNames = new Set<string>(items.map((i) => i.name));
  const errors: string[] = [];

  const depGraph: Record<string, string[]> = {};

  for (const item of items) {
    if (seen.has(item.name)) errors.push(`Duplicate name: ${item.name}`);
    seen.add(item.name);

    if (!/^[a-z0-9-]+$/.test(item.name)) {
      errors.push(`Invalid name (kebab-case only): ${item.name}`);
    }

    depGraph[item.name] = [...(item.registryDependencies ?? [])];

    for (const dep of item.registryDependencies ?? []) {
      if (!allNames.has(dep)) {
        errors.push(`${item.name}: missing registryDependency '${dep}'`);
      }
    }
    for (const rel of item.related ?? []) {
      if (!allNames.has(rel)) {
        errors.push(`${item.name}: missing related '${rel}'`);
      }
    }

    for (const f of item.files) {
      const expectedDir = `components/${areaFor(item)}/`;
      if (!f.path.startsWith(expectedDir)) {
        errors.push(`${item.name}: file ${f.path} not under ${expectedDir}`);
      }
    }
  }

  // Cycle detection on registryDependencies (DFS with three-color marking).
  const WHITE = 0,
    GRAY = 1,
    BLACK = 2;
  const color: Record<string, number> = {};
  for (const name of Object.keys(depGraph)) color[name] = WHITE;

  function dfs(node: string, stack: string[]): void {
    color[node] = GRAY;
    stack.push(node);
    for (const next of depGraph[node] ?? []) {
      if (color[next] === GRAY) {
        const cycleStart = stack.indexOf(next);
        const cycle = [...stack.slice(cycleStart), next].join(" -> ");
        errors.push(`Cycle in registryDependencies: ${cycle}`);
        continue;
      }
      if (color[next] === WHITE && depGraph[next] !== undefined) {
        dfs(next, stack);
      }
    }
    stack.pop();
    color[node] = BLACK;
  }
  for (const name of Object.keys(depGraph)) {
    if (color[name] === WHITE) dfs(name, []);
  }

  if (errors.length) {
    console.error("Registry validation failed:");
    for (const e of errors) console.error("  - " + e);
    process.exit(1);
  }
}

function indexEntry(item: RegistryItem): string {
  const area = areaFor(item);
  const importPath = `@/components/${area}/${item.name}`;
  const lazyImport =
    area === "ui"
      ? "undefined" // primitives are not lazy-rendered in showcase
      : `React.lazy(() => import("${importPath}"))`;

  // Strip Component from the JSON since it's a function reference.
  const meta = JSON.stringify(item, null, 2)
    .split("\n")
    .map((l) => "  " + l)
    .join("\n")
    .trimStart();

  return `  ${JSON.stringify(item.name)}: {
    meta: ${meta},
    Component: ${lazyImport},
  }`;
}

function build(): void {
  const all = [...uiItems, ...exampleItems, ...blockItems];
  validate(all);

  const banner = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly. Run \`pnpm registry:build\`.

import * as React from "react";

import type { RegistryItem } from "@/lib/registry-schema";

export type RegistryIndexEntry = {
  meta: RegistryItem;
  Component?: React.ComponentType;
};

export const Index: Record<string, RegistryIndexEntry> = {
${all.map(indexEntry).join(",\n")},
};

export const ItemsByArea = {
  ui: ${JSON.stringify(uiItems.map((i) => i.name))},
  examples: ${JSON.stringify(exampleItems.map((i) => i.name))},
  blocks: ${JSON.stringify(blockItems.map((i) => i.name))},
};

export const ExamplesBySlug: Record<string, string[]> = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(
        exampleItems.reduce<Record<string, string[]>>((acc, item) => {
          if (!item.slug) return acc;
          (acc[item.slug] ??= []).push(item.name);
          return acc;
        }, {}),
      ),
    ),
    null,
    2,
  )};
`;

  fs.writeFileSync(OUTPUT, banner);
  console.log(`Wrote ${OUTPUT} (${all.length} items)`);
}

build();
