/**
 * Emit docs/new-components.md — every primitive whose `proposedGroup` is set
 * (i.e. surfaces under "New Components" on /showcase). Includes path, upstream
 * URL, description, registry deps, deviations, and the variant/example list.
 *
 * Run: pnpm tsx scripts/generate-new-components-doc.ts
 */
import * as fs from "node:fs";
import * as path from "node:path";

import { items as uiItems } from "../src/components/ui/_registry";
import { items as exampleItems } from "../src/components/examples/_registry";
import type { RegistryItem } from "../src/lib/registry-schema";

const REPO_ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.join(REPO_ROOT, "docs/new-components.md");

const newPrimitives = uiItems.filter((i) => i.proposedGroup);

const examplesBySlug = new Map<string, RegistryItem[]>();
for (const ex of exampleItems) {
  if (!ex.slug) continue;
  if (!examplesBySlug.has(ex.slug)) examplesBySlug.set(ex.slug, []);
  examplesBySlug.get(ex.slug)!.push(ex);
}

const groups = new Map<string, RegistryItem[]>();
for (const item of newPrimitives) {
  const g = item.proposedGroup!;
  if (!groups.has(g)) groups.set(g, []);
  groups.get(g)!.push(item);
}

function renderItem(item: RegistryItem): string {
  const lines: string[] = [];
  lines.push(`### ${item.title ?? item.name}`);
  lines.push("");
  lines.push(`**name** \`${item.name}\``);
  if (item.upstreamUrl) lines.push(`**upstream** [${item.upstreamUrl}](${item.upstreamUrl})`);
  const filePaths = item.files.map((f) => `\`src/${f.path}\``).join(", ");
  lines.push(`**files** ${filePaths}`);
  if (item.description) {
    lines.push("");
    lines.push(item.description);
  }
  if (item.registryDependencies?.length) {
    lines.push("");
    lines.push(`**deps** ${item.registryDependencies.map((d) => `\`${d}\``).join(", ")}`);
  }
  if (item.related?.length) {
    lines.push(`**related** ${item.related.map((d) => `\`${d}\``).join(", ")}`);
  }
  if (item.categories?.length) {
    lines.push(`**categories** ${item.categories.join(", ")}`);
  }
  if (item.deviations?.length) {
    lines.push("");
    lines.push("**deviations**");
    for (const d of item.deviations) lines.push(`- ${d}`);
  }

  const variants = examplesBySlug.get(item.name) ?? [];
  if (variants.length > 0) {
    lines.push("");
    lines.push(`**variants** (${variants.length})`);
    lines.push("");
    lines.push("| variant | title | file |");
    lines.push("|---|---|---|");
    for (const v of variants) {
      const filePath = v.files[0]?.path ?? "";
      lines.push(`| \`${v.variant ?? v.name}\` | ${v.title ?? ""} | \`src/${filePath}\` |`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

function renderGroup(group: string, items: RegistryItem[]): string {
  const sorted = [...items].sort((a, b) => a.name.localeCompare(b.name));
  return [`## ${group}`, "", ...sorted.map(renderItem)].join("\n");
}

const sortedGroups = [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]));

const totalVariants = newPrimitives.reduce(
  (n, i) => n + (examplesBySlug.get(i.name)?.length ?? 0),
  0,
);

const head = [
  "# New Components",
  "",
  "> Components beyond canonical shadcn/ui, sourced from external registries. Live under `New Components` on `/showcase`. Generated by `pnpm tsx scripts/generate-new-components-doc.ts`. Do not edit by hand.",
  "",
  `**Primitives:** ${newPrimitives.length}  ·  **Variants:** ${totalVariants}  ·  **Groups:** ${sortedGroups.length}`,
  "",
  "**Groups in this doc:** " + sortedGroups.map(([g]) => `[${g}](#${g})`).join(" · "),
  "",
  "---",
  "",
];

const body = sortedGroups.map(([g, items]) => renderGroup(g, items)).join("\n");

// Section 2: variants from external registries that share a slug with a
// canonical shadcn primitive. These do NOT show under "New Components" on
// /showcase (they render under their shadcn slug section), but they are
// flagged with a red "Not in spec" pill. Surface them here so the catalog
// is complete.
const SHADCN_DOMAIN = "ui.shadcn.com";
const shadcnPrimitiveNames = new Set(uiItems.filter((i) => !i.proposedGroup).map((i) => i.name));
const flaggedExternal = exampleItems.filter(
  (ex) =>
    ex.upstreamUrl &&
    !ex.upstreamUrl.includes(SHADCN_DOMAIN) &&
    ex.slug &&
    shadcnPrimitiveNames.has(ex.slug),
);

const flaggedBySlug = new Map<string, RegistryItem[]>();
for (const ex of flaggedExternal) {
  const slug = ex.slug!;
  if (!flaggedBySlug.has(slug)) flaggedBySlug.set(slug, []);
  flaggedBySlug.get(slug)!.push(ex);
}

function renderFlaggedSection(): string {
  if (flaggedBySlug.size === 0) return "";
  const lines: string[] = [
    "",
    "---",
    "",
    "## External variants under shadcn slugs",
    "",
    `> ${flaggedExternal.length} variants from external registries that share a slug with a canonical shadcn primitive. These render under their shadcn section on \`/showcase\` (with a red "Not in spec" pill, \`isFlagged: true\`), not under "New Components". Listed here for completeness.`,
    "",
  ];
  const sortedSlugs = [...flaggedBySlug.keys()].sort();
  for (const slug of sortedSlugs) {
    const variants = flaggedBySlug.get(slug)!;
    lines.push(`### ${slug} (${variants.length})`);
    lines.push("");
    lines.push("| name | upstream | file |");
    lines.push("|---|---|---|");
    for (const v of variants.sort((a, b) => a.name.localeCompare(b.name))) {
      const filePath = v.files[0]?.path ?? "";
      const url = v.upstreamUrl ?? "";
      lines.push(`| \`${v.name}\` | [${url}](${url}) | \`src/${filePath}\` |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

const flaggedBody = renderFlaggedSection();

// Update head with combined totals
const head2 = [
  "# New Components",
  "",
  "> Components beyond canonical shadcn/ui, sourced from external registries. Generated by `pnpm tsx scripts/generate-new-components-doc.ts`. Do not edit by hand.",
  "",
  `**Primitives (own slug, render in "New Components" band):** ${newPrimitives.length}  ·  **Their variants:** ${totalVariants}  ·  **Groups:** ${sortedGroups.length}`,
  "",
  `**Variants under shadcn slugs (flagged "Not in spec"):** ${flaggedExternal.length} across ${flaggedBySlug.size} slugs`,
  "",
  "**Groups in this doc:** " + sortedGroups.map(([g]) => `[${g}](#${g})`).join(" · "),
  "",
  "---",
  "",
];

fs.writeFileSync(OUTPUT, head2.join("\n") + body + flaggedBody + "\n", "utf8");
console.log(
  `Wrote ${OUTPUT} — ${newPrimitives.length} primitives, ${totalVariants} variants, ${sortedGroups.length} groups + ${flaggedExternal.length} flagged variants under shadcn slugs.`,
);
