import { defineItems } from "@/lib/registry-schema";

/**
 * Example entries for the display-group source file. Populated by Phase 2
 * extraction for that group. Append items here as you extract each <Demo>
 * into its own `<slug>-<variant>.tsx` example file.
 */
export const items = defineItems([
  // avatar
  {
    name: "avatar-default",
    type: "registry:example",
    title: "Default",
    description:
      "Hero showcase composing solo avatar, badged avatar, and an avatar group with overflow count.",
    slug: "avatar",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    span: 2,
  },
  {
    name: "avatar-basic",
    type: "registry:example",
    title: "Basic",
    description: "Single avatar with image and fallback initials.",
    slug: "avatar",
    variant: "basic",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-basic.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "avatar-badge",
    type: "registry:example",
    title: "Badge",
    description: "Avatar with a status dot badge to indicate online presence.",
    slug: "avatar",
    variant: "badge",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-badge.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "avatar-badge-with-icon",
    type: "registry:example",
    title: "Badge with Icon",
    description: "Avatar with an icon badge overlay (e.g. plus / add).",
    slug: "avatar",
    variant: "badge-with-icon",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-badge-with-icon.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "avatar-avatar-group",
    type: "registry:example",
    title: "Avatar Group",
    description: "Stacked group of overlapping avatars.",
    slug: "avatar",
    variant: "avatar-group",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-avatar-group.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "avatar-avatar-group-count",
    type: "registry:example",
    title: "Avatar Group Count",
    description: "Avatar group with a trailing overflow count chip.",
    slug: "avatar",
    variant: "avatar-group-count",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-avatar-group-count.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "avatar-avatar-group-with-icon",
    type: "registry:example",
    title: "Avatar Group with Icon",
    description: "Avatar group with an icon (plus) trailing overflow indicator.",
    slug: "avatar",
    variant: "avatar-group-with-icon",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-avatar-group-with-icon.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "avatar-sizes",
    type: "registry:example",
    title: "Sizes",
    description: "Avatar size variants: sm, default, lg.",
    slug: "avatar",
    variant: "sizes",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "components/examples/avatar-sizes.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "avatar-dropdown",
    type: "registry:example",
    title: "Dropdown",
    description:
      "Avatar used as a dropdown menu trigger for account actions (profile, billing, settings, log out).",
    slug: "avatar",
    variant: "dropdown",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    registryDependencies: ["avatar", "button", "dropdown-menu"],
    files: [
      {
        path: "components/examples/avatar-dropdown.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },

  // badge
  {
    name: "badge-default",
    type: "registry:example",
    title: "Default",
    description: "Hero showcase of all badge variants: default, secondary, destructive, outline.",
    slug: "badge",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    registryDependencies: ["badge"],
    files: [
      {
        path: "components/examples/badge-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    span: 2,
  },
  {
    name: "badge-variants",
    type: "registry:example",
    title: "Variants",
    description:
      "All badge variants side by side: default, secondary, destructive, outline, ghost.",
    slug: "badge",
    variant: "variants",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    registryDependencies: ["badge"],
    files: [
      {
        path: "components/examples/badge-variants.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    span: 2,
  },
  {
    name: "badge-with-icon",
    type: "registry:example",
    title: "With Icon",
    description: "Badges that include a leading or trailing lucide icon.",
    slug: "badge",
    variant: "with-icon",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    registryDependencies: ["badge"],
    files: [
      {
        path: "components/examples/badge-with-icon.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "badge-with-spinner",
    type: "registry:example",
    title: "With Spinner",
    description: "Badges with a leading or trailing spinner for in-progress state.",
    slug: "badge",
    variant: "with-spinner",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    registryDependencies: ["badge", "spinner"],
    files: [
      {
        path: "components/examples/badge-with-spinner.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "badge-link",
    type: "registry:example",
    title: "Link",
    description: "Badge composed as an anchor via asChild for navigation chips.",
    slug: "badge",
    variant: "link",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    registryDependencies: ["badge"],
    files: [{ path: "components/examples/badge-link.tsx", type: "registry:example" }],
    categories: ["display"],
  },
  {
    name: "badge-custom-colors",
    type: "registry:example",
    title: "Custom Colors",
    description:
      "Badges with bespoke Tailwind palette classes for brand or status colors outside the design tokens.",
    slug: "badge",
    variant: "custom-colors",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    registryDependencies: ["badge"],
    files: [
      {
        path: "components/examples/badge-custom-colors.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    span: 2,
  },

  // calendar
  {
    name: "calendar-default",
    type: "registry:example",
    title: "Default",
    description: "Hero single-date calendar with month/year dropdown caption (project deviation).",
    slug: "calendar",
    variant: "default",
    isDefault: true,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar"],
    files: [
      {
        path: "components/examples/calendar-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
    height: "tall",
  },
  {
    name: "calendar-basic",
    type: "registry:example",
    title: "Basic",
    description: "Plain single-date calendar.",
    slug: "calendar",
    variant: "basic",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar"],
    files: [
      {
        path: "components/examples/calendar-basic.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
  },
  {
    name: "calendar-range-calendar",
    type: "registry:example",
    title: "Range Calendar",
    description:
      "Two-month range picker with from/to selection, disabling future and pre-1900 dates.",
    slug: "calendar",
    variant: "range-calendar",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar", "card"],
    files: [
      {
        path: "components/examples/calendar-range-calendar.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
    span: 2,
    height: "tall",
  },
  {
    name: "calendar-month-and-year-selector",
    type: "registry:example",
    title: "Month and Year Selector",
    description: "Calendar with dropdown month and year navigation in the caption.",
    slug: "calendar",
    variant: "month-and-year-selector",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar"],
    files: [
      {
        path: "components/examples/calendar-month-and-year-selector.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
  },
  {
    name: "calendar-presets",
    type: "registry:example",
    title: "Presets",
    description:
      "Calendar wrapped in a card with preset buttons (Today, Tomorrow, In 3 days, In a week, In 2 weeks).",
    slug: "calendar",
    variant: "presets",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar", "card", "button"],
    files: [
      {
        path: "components/examples/calendar-presets.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
    height: "tall",
  },
  {
    name: "calendar-date-and-time-picker",
    type: "registry:example",
    title: "Date and Time Picker",
    description:
      "Calendar with paired Start/End time inputs in the card footer using input-group with a clock icon.",
    slug: "calendar",
    variant: "date-and-time-picker",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar", "card", "field", "input-group"],
    files: [
      {
        path: "components/examples/calendar-date-and-time-picker.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
    span: 2,
    height: "tall",
  },
  {
    name: "calendar-booked-dates",
    type: "registry:example",
    title: "Booked dates",
    description:
      "Calendar with a range of booked (disabled) dates rendered with a strike-through modifier.",
    slug: "calendar",
    variant: "booked-dates",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar", "card"],
    files: [
      {
        path: "components/examples/calendar-booked-dates.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
    height: "tall",
  },
  {
    name: "calendar-custom-cell-size",
    type: "registry:example",
    title: "Custom Cell Size",
    description:
      "Range calendar with enlarged cells and custom DayButton showing per-day pricing (weekend vs weekday).",
    slug: "calendar",
    variant: "custom-cell-size",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar", "card"],
    files: [
      {
        path: "components/examples/calendar-custom-cell-size.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
    span: 2,
    height: "tall",
  },
  {
    name: "calendar-week-numbers",
    type: "registry:example",
    title: "Week Numbers",
    description: "Calendar with the ISO week number column on the left.",
    slug: "calendar",
    variant: "week-numbers",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar", "card"],
    files: [
      {
        path: "components/examples/calendar-week-numbers.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
    height: "tall",
  },
  {
    name: "calendar-with-timezone",
    type: "registry:example",
    title: "With Timezone",
    description:
      "Calendar pinned to a specific timezone (Europe/Prague) for off-server selections.",
    slug: "calendar",
    variant: "with-timezone",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar"],
    files: [
      {
        path: "components/examples/calendar-with-timezone.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
  },
  {
    name: "calendar-hijri",
    type: "registry:example",
    title: "Hijri",
    description: "Calendar in right-to-left direction for Hijri-style locales.",
    slug: "calendar",
    variant: "hijri",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    registryDependencies: ["calendar"],
    files: [
      {
        path: "components/examples/calendar-hijri.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "display"],
  },

  // chart
  {
    name: "chart-default",
    type: "registry:example",
    title: "Default",
    description:
      "Hero interactive bar chart card with toggle between desktop and mobile totals over 30 days.",
    slug: "chart",
    variant: "default",
    isDefault: true,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart", "card"],
    files: [
      {
        path: "components/examples/chart-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "chart-your-first-chart",
    type: "registry:example",
    title: "Your First Chart",
    description:
      "Minimal bar chart with grid, axis, tooltip, legend wired to the shared chart config.",
    slug: "chart",
    variant: "your-first-chart",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-your-first-chart.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
    span: 2,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "chart-chart-config",
    type: "registry:example",
    title: "Chart Config",
    description:
      "Demonstrates a ChartConfig entry with an icon and per-theme color (light/dark hex tokens).",
    slug: "chart",
    variant: "chart-config",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-chart-config.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "chart-tooltip",
    type: "registry:example",
    title: "Tooltip",
    description: "Bar chart with the dot-indicator variant of the shared chart tooltip.",
    slug: "chart",
    variant: "tooltip",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-tooltip.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
    span: 2,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "chart-legend",
    type: "registry:example",
    title: "Legend",
    description: "Bar chart with the shared chart legend below the plot.",
    slug: "chart",
    variant: "legend",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-legend.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "chart-bar-chart",
    type: "registry:example",
    title: "Bar chart",
    description: "Bare bar chart with a single series and rounded corners.",
    slug: "chart",
    variant: "bar-chart",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-bar-chart.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
  },
  {
    name: "chart-with-grid",
    type: "registry:example",
    title: "With grid",
    description: "Bar chart with a horizontal cartesian grid.",
    slug: "chart",
    variant: "with-grid",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-with-grid.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
  },
  {
    name: "chart-with-axis",
    type: "registry:example",
    title: "With axis",
    description: "Bar chart with grid plus an X axis labeled by month.",
    slug: "chart",
    variant: "with-axis",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-with-axis.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
  },
  {
    name: "chart-with-tooltip",
    type: "registry:example",
    title: "With tooltip",
    description: "Bar chart with grid, axis, and dot-indicator chart tooltip on two series.",
    slug: "chart",
    variant: "with-tooltip",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-with-tooltip.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
  },
  {
    name: "chart-with-legend",
    type: "registry:example",
    title: "With legend",
    description: "Bar chart with grid, axis, tooltip, and legend on two series.",
    slug: "chart",
    variant: "with-legend",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-with-legend.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
    span: 2,
  },
  {
    name: "chart-tooltip-demo",
    type: "registry:example",
    title: "Tooltip Demo",
    description: "Bar chart variant using the line-indicator tooltip style.",
    slug: "chart",
    variant: "tooltip-demo",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    registryDependencies: ["chart"],
    files: [
      {
        path: "components/examples/chart-tooltip-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data-viz"],
  },

  // data-table
  {
    name: "data-table-default",
    type: "registry:example",
    title: "Default",
    description:
      "Hero interactive TanStack table with sort, filter, column visibility, row selection, pagination, and per-row actions menu.",
    slug: "data-table",
    variant: "default",
    isDefault: true,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table", "button", "checkbox", "dropdown-menu", "input"],
    files: [
      {
        path: "components/examples/data-table-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
  },
  {
    name: "data-table-basic-table",
    type: "registry:example",
    title: "Basic Table",
    description: "Minimal TanStack table over the Payments fixture.",
    slug: "data-table",
    variant: "basic-table",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table"],
    files: [
      {
        path: "components/examples/data-table-basic-table.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "data-table-cell-formatting",
    type: "registry:example",
    title: "Cell Formatting",
    description: "TanStack table with a right-aligned currency-formatted Amount cell.",
    slug: "data-table",
    variant: "cell-formatting",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table"],
    files: [
      {
        path: "components/examples/data-table-cell-formatting.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "data-table-row-actions",
    type: "registry:example",
    title: "Row Actions",
    description: "TanStack table with a per-row dropdown menu for copy/view actions.",
    slug: "data-table",
    variant: "row-actions",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table", "button", "dropdown-menu"],
    files: [
      {
        path: "components/examples/data-table-row-actions.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "data-table-pagination",
    type: "registry:example",
    title: "Pagination",
    description:
      "TanStack table with Previous/Next pagination controls and a fixed page size of 3.",
    slug: "data-table",
    variant: "pagination",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table", "button"],
    files: [
      {
        path: "components/examples/data-table-pagination.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "data-table-sorting",
    type: "registry:example",
    title: "Sorting",
    description:
      "TanStack table with a click-to-sort Email column header using ArrowUpDown indicator.",
    slug: "data-table",
    variant: "sorting",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table", "button"],
    files: [
      {
        path: "components/examples/data-table-sorting.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "data-table-filtering",
    type: "registry:example",
    title: "Filtering",
    description: "TanStack table with a text input filtering the email column.",
    slug: "data-table",
    variant: "filtering",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table", "input"],
    files: [
      {
        path: "components/examples/data-table-filtering.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "data-table-visibility",
    type: "registry:example",
    title: "Visibility",
    description: "TanStack table with a Columns dropdown menu for toggling column visibility.",
    slug: "data-table",
    variant: "visibility",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table", "button", "dropdown-menu"],
    files: [
      {
        path: "components/examples/data-table-visibility.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "data-table-row-selection",
    type: "registry:example",
    title: "Row Selection",
    description:
      "TanStack table with a select-all header checkbox, per-row checkboxes, and a selected-row count footer.",
    slug: "data-table",
    variant: "row-selection",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/data-table",
    registryDependencies: ["table", "checkbox"],
    files: [
      {
        path: "components/examples/data-table-row-selection.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 3,
    height: "tall",
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },

  // skeleton
  {
    name: "skeleton-default",
    type: "registry:example",
    title: "Default",
    description: "Hero loading placeholder: circular avatar skeleton plus two text-line skeletons.",
    slug: "skeleton",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "components/examples/skeleton-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "skeleton-avatar",
    type: "registry:example",
    title: "Avatar",
    description: "Compact avatar-and-name skeleton: a circle plus two stacked text bars.",
    slug: "skeleton",
    variant: "avatar",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "components/examples/skeleton-avatar.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "skeleton-card",
    type: "registry:example",
    title: "Card",
    description: "Card placeholder with two header lines and a video-aspect content block.",
    slug: "skeleton",
    variant: "card",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    registryDependencies: ["skeleton", "card"],
    files: [
      {
        path: "components/examples/skeleton-card.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "skeleton-text",
    type: "registry:example",
    title: "Text",
    description: "Three stacked line skeletons of varying widths for a paragraph placeholder.",
    slug: "skeleton",
    variant: "text",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "components/examples/skeleton-text.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "skeleton-form",
    type: "registry:example",
    title: "Form",
    description: "Form placeholder: two label/input pairs plus a button skeleton.",
    slug: "skeleton",
    variant: "form",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "components/examples/skeleton-form.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "skeleton-table",
    type: "registry:example",
    title: "Table",
    description:
      "Five-row table placeholder with one flexible column and two fixed-width columns per row.",
    slug: "skeleton",
    variant: "table",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "components/examples/skeleton-table.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },

  // table
  {
    name: "table-default",
    type: "registry:example",
    title: "Default",
    description:
      "Hero static table with header, body, footer (totals), and caption listing recent invoices.",
    slug: "table",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/table",
    registryDependencies: ["table"],
    files: [
      {
        path: "components/examples/table-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 2,
  },
  {
    name: "table-footer",
    type: "registry:example",
    title: "Footer",
    description: "Static table with a footer total row over the first three invoices.",
    slug: "table",
    variant: "footer",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/table",
    registryDependencies: ["table"],
    files: [
      {
        path: "components/examples/table-footer.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 2,
  },
  {
    name: "table-actions",
    type: "registry:example",
    title: "Actions",
    description: "Static product table with a per-row actions dropdown (Edit, Duplicate, Delete).",
    slug: "table",
    variant: "actions",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.shadcn.com/docs/components/table",
    registryDependencies: ["table", "button", "dropdown-menu"],
    files: [
      {
        path: "components/examples/table-actions.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
    span: 2,
  },

  // typography
  {
    name: "typography-h1",
    type: "registry:example",
    title: "h1",
    description: "Page heading: extrabold, 4xl, tight tracking, balanced wrap.",
    slug: "typography",
    variant: "h1",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-h1.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-h2",
    type: "registry:example",
    title: "h2",
    description: "Section heading: 3xl, semibold, with a bottom border.",
    slug: "typography",
    variant: "h2",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-h2.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-h3",
    type: "registry:example",
    title: "h3",
    description: "Subsection heading: 2xl, semibold.",
    slug: "typography",
    variant: "h3",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-h3.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-h4",
    type: "registry:example",
    title: "h4",
    description: "Block heading: xl, semibold.",
    slug: "typography",
    variant: "h4",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-h4.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-p",
    type: "registry:example",
    title: "p",
    description: "Body paragraph with leading-7 and a top margin when not first.",
    slug: "typography",
    variant: "p",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-p.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-blockquote",
    type: "registry:example",
    title: "blockquote",
    description: "Italic blockquote with a left accent border.",
    slug: "typography",
    variant: "blockquote",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-blockquote.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-table",
    type: "registry:example",
    title: "table",
    description: "Native HTML table styled per the typography scale: bordered cells, zebra rows.",
    slug: "typography",
    variant: "table",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-table.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    span: 2,
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-list",
    type: "registry:example",
    title: "list",
    description: "Disc-bulleted unordered list with margin-top between items.",
    slug: "typography",
    variant: "list",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-list.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-inline-code",
    type: "registry:example",
    title: "Inline code",
    description: "Inline `<code>` styled with a muted background and mono font.",
    slug: "typography",
    variant: "inline-code",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-inline-code.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-lead",
    type: "registry:example",
    title: "Lead",
    description: "Lead paragraph: xl text in muted-foreground color for intros.",
    slug: "typography",
    variant: "lead",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-lead.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-large",
    type: "registry:example",
    title: "Large",
    description: "Large prompt: lg text, semibold, used in dialog questions.",
    slug: "typography",
    variant: "large",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-large.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-small",
    type: "registry:example",
    title: "Small",
    description: "Small label: sm text, leading-none, medium weight.",
    slug: "typography",
    variant: "small",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-small.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-muted",
    type: "registry:example",
    title: "Muted",
    description: "Muted helper line: sm text in muted-foreground color.",
    slug: "typography",
    variant: "muted",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-muted.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: [
      "Upstream MD has no ## Examples block; this variant comes from an H2 section under the slug's docs page.",
    ],
  },
  {
    name: "typography-demo",
    type: "registry:example",
    title: "Demo",
    description:
      "Long-form composition exercising every typography scale level: h1, h2, h3, p, blockquote, list, table.",
    slug: "typography",
    variant: "demo",
    isDefault: false,
    isFlagged: true,
    upstreamUrl: "https://ui.shadcn.com/docs/components/typography",
    registryDependencies: [],
    files: [
      {
        path: "components/examples/typography-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    span: 3,
  },
]);
