import { defineItems } from "@/lib/registry-schema";

/**
 * Example entries for effects / animation components (Aceternity and similar).
 */
export const items = defineItems([
  {
    name: "noise-background-default",
    type: "registry:example",
    title: "Default",
    description:
      "Animated gradient background with noise overlay wrapping a pill button, demonstrating spring-physics movement.",
    slug: "noise-background",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://ui.aceternity.com/components/noise-background",
    registryDependencies: ["noise-background"],
    files: [
      {
        path: "components/examples/noise-background-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "effects"],
    deviations: [
      "Noise texture served from /noise.webp instead of external CDN.",
      "Token classes replace hardcoded neutral palette.",
    ],
  },
  {
    name: "noise-background-card",
    type: "registry:example",
    title: "Card",
    description:
      "Noise background wrapping a card component with image placeholder and text content, showing container composition.",
    slug: "noise-background",
    variant: "card",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://ui.aceternity.com/components/noise-background",
    registryDependencies: ["noise-background", "card"],
    files: [
      {
        path: "components/examples/noise-background-card.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "effects"],
    deviations: [
      "Token classes replace hardcoded neutral palette.",
      "Self-hosted noise texture.",
      "External image replaced with placeholder.",
    ],
  },
  {
    name: "stateful-button-default",
    type: "registry:example",
    title: "Default",
    description:
      "Button that cycles through idle, loading spinner, and success check states on click with motion/react animations.",
    slug: "stateful-button",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://ui.aceternity.com/components/stateful-button",
    registryDependencies: ["stateful-button"],
    files: [
      {
        path: "components/examples/stateful-button-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["actions", "effects"],
    deviations: [
      "Renamed export from Button to StatefulButton to avoid conflict.",
      "Token classes replace hardcoded green palette.",
    ],
  },
  {
    name: "multi-step-loader-default",
    type: "registry:example",
    title: "Default",
    description:
      "Full-screen loader overlay cycling through named steps with animated check marks, triggered by a button click.",
    slug: "multi-step-loader",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://ui.aceternity.com/components/multi-step-loader",
    registryDependencies: ["multi-step-loader", "button"],
    files: [
      {
        path: "components/examples/multi-step-loader-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback", "effects"],
    deviations: ["Token classes replace hardcoded black/white/lime palette."],
  },
  {
    name: "separator-extended-default",
    type: "registry:example",
    title: "Default",
    description:
      "Solid separator in a composition layout with skeleton blocks, horizontal OR dividers, and vertical side separators.",
    slug: "separator-extended",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://basecn.dev/docs/components/separator-extended",
    registryDependencies: ["separator-extended"],
    files: [
      {
        path: "components/examples/separator-extended-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["layout"],
    deviations: [
      "Renamed Separator to SeparatorExtended to avoid conflict with existing primitive.",
    ],
  },
  {
    name: "separator-extended-dashed",
    type: "registry:example",
    title: "Dashed",
    description:
      "Dashed separator variant in the same composition layout showing horizontal and vertical usage.",
    slug: "separator-extended",
    variant: "dashed",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://basecn.dev/docs/components/separator-extended",
    registryDependencies: ["separator-extended"],
    files: [
      {
        path: "components/examples/separator-extended-dashed.tsx",
        type: "registry:example",
      },
    ],
    categories: ["layout"],
    deviations: [
      "Renamed Separator to SeparatorExtended to avoid conflict with existing primitive.",
    ],
  },
  {
    name: "separator-extended-dotted",
    type: "registry:example",
    title: "Dotted",
    description:
      "Dotted separator variant in the same composition layout showing horizontal and vertical usage.",
    slug: "separator-extended",
    variant: "dotted",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://basecn.dev/docs/components/separator-extended",
    registryDependencies: ["separator-extended"],
    files: [
      {
        path: "components/examples/separator-extended-dotted.tsx",
        type: "registry:example",
      },
    ],
    categories: ["layout"],
    deviations: [
      "Renamed Separator to SeparatorExtended to avoid conflict with existing primitive.",
    ],
  },
  {
    name: "separator-extended-double",
    type: "registry:example",
    title: "Double",
    description:
      "Double-line separator variant in the same composition layout showing horizontal and vertical usage.",
    slug: "separator-extended",
    variant: "double",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://basecn.dev/docs/components/separator-extended",
    registryDependencies: ["separator-extended"],
    files: [
      {
        path: "components/examples/separator-extended-double.tsx",
        type: "registry:example",
      },
    ],
    categories: ["layout"],
    deviations: [
      "Renamed Separator to SeparatorExtended to avoid conflict with existing primitive.",
    ],
  },
  // card-styles (cardcn.dev)
  {
    name: "card-styles-shadow",
    type: "registry:example",
    title: "Shadow",
    description: "Card with retro offset shadow using --border token for a bold, playful look.",
    slug: "card-styles",
    variant: "shadow",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    registryDependencies: ["card"],
    files: [
      {
        path: "components/examples/card-styles-shadow.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: ["Adapted from cardcn card-1."],
  },
  {
    name: "card-styles-lines",
    type: "registry:example",
    title: "Lines",
    description: "Card framed by gradient border lines creating a technical blueprint aesthetic.",
    slug: "card-styles",
    variant: "lines",
    isFlagged: false,
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    registryDependencies: ["card"],
    files: [
      {
        path: "components/examples/card-styles-lines.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: ["Adapted from cardcn card-2. Gradient uses token border color."],
  },
  {
    name: "card-styles-hatched",
    type: "registry:example",
    title: "Hatched",
    description: "Card with diagonal hatching pattern behind transparent content area.",
    slug: "card-styles",
    variant: "hatched",
    isFlagged: false,
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    registryDependencies: ["card"],
    files: [
      {
        path: "components/examples/card-styles-hatched.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: ["Adapted from cardcn card-10. Hatching uses --border token."],
  },
  {
    name: "card-styles-aurora",
    type: "registry:example",
    title: "Aurora",
    description: "Card with subtle radial gradient aurora glow effect behind transparent content.",
    slug: "card-styles",
    variant: "aurora",
    isFlagged: false,
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    registryDependencies: ["card"],
    files: [
      {
        path: "components/examples/card-styles-aurora.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: ["Adapted from cardcn card-14."],
  },
  {
    name: "card-styles-tilted",
    type: "registry:example",
    title: "Tilted",
    description: "Card with a rotated background layer creating a tilted shadow depth effect.",
    slug: "card-styles",
    variant: "tilted",
    isFlagged: false,
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    registryDependencies: ["card"],
    files: [
      {
        path: "components/examples/card-styles-tilted.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: ["Adapted from cardcn card-15."],
  },
  {
    name: "card-styles-stacked",
    type: "registry:example",
    title: "Stacked",
    description:
      "Card with two scaled-down layers behind it creating a stacked paper depth effect.",
    slug: "card-styles",
    variant: "stacked",
    isFlagged: false,
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    registryDependencies: ["card"],
    files: [
      {
        path: "components/examples/card-styles-stacked.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
    deviations: ["Adapted from cardcn card-18."],
  },
  // autocomplete (coss.com)
  {
    name: "autocomplete-default",
    type: "registry:example",
    title: "Default",
    description:
      "Autocomplete input filtering a list of frameworks with clear button and empty state message.",
    slug: "autocomplete",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://coss.com/ui/docs/components/autocomplete",
    registryDependencies: ["autocomplete"],
    files: [
      {
        path: "components/examples/autocomplete-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
    deviations: [
      "Uses native input styling instead of coss Input primitive.",
      "ScrollArea without coss-specific props.",
    ],
  },
  {
    name: "action-bar-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Action Bar component showing core functionality.",
    slug: "action-bar",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/action-bar",
    registryDependencies: ["action-bar"],
    files: [
      {
        path: "components/examples/action-bar-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["actions"],
  },
  {
    name: "banner-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Banner component showing core functionality.",
    slug: "banner",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/banner",
    registryDependencies: ["banner"],
    files: [
      {
        path: "components/examples/banner-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "border-beam-button-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Border Beam Button component showing core functionality.",
    slug: "border-beam-button",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.cult-ui.com/docs/components/border-beam-button",
    registryDependencies: ["border-beam-button"],
    files: [
      {
        path: "components/examples/border-beam-button-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["buttons"],
  },
  {
    name: "circular-progress-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Circular Progress component showing core functionality.",
    slug: "circular-progress",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/circular-progress",
    registryDependencies: ["circular-progress"],
    files: [
      {
        path: "components/examples/circular-progress-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "color-picker-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Color Picker component showing core functionality.",
    slug: "color-picker",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/color-picker",
    registryDependencies: ["color-picker"],
    files: [
      {
        path: "components/examples/color-picker-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "color-swatch-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Color Swatch component showing core functionality.",
    slug: "color-swatch",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/color-swatch",
    registryDependencies: ["color-swatch"],
    files: [
      {
        path: "components/examples/color-swatch-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "cropper-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Cropper component showing core functionality.",
    slug: "cropper",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.diceui.com/docs/components/radix/cropper",
    registryDependencies: ["cropper"],
    files: [
      {
        path: "components/examples/cropper-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "cropper-circular",
    type: "registry:example",
    title: "Circular",
    description:
      "Circular crop area with 1:1 aspect ratio, ideal for avatar or profile photo selection.",
    slug: "cropper",
    variant: "circular",
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.diceui.com/docs/components/radix/cropper",
    registryDependencies: ["cropper"],
    files: [
      {
        path: "components/examples/cropper-circular.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "cropper-with-controls",
    type: "registry:example",
    title: "With Controls",
    description:
      "Cropper with zoom slider, rotation slider, and reset button for precise image adjustments.",
    slug: "cropper",
    variant: "with-controls",
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.diceui.com/docs/components/radix/cropper",
    registryDependencies: ["cropper", "slider", "button"],
    files: [
      {
        path: "components/examples/cropper-with-controls.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "data-grid-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Data Grid component showing core functionality.",
    slug: "data-grid",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://www.diceui.com/docs/components/radix/data-grid",
    registryDependencies: ["data-grid"],
    files: [
      {
        path: "components/examples/data-grid-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["data"],
  },
  {
    name: "file-upload-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for File Upload component showing core functionality.",
    slug: "file-upload",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/file-upload",
    registryDependencies: ["file-upload"],
    files: [
      {
        path: "components/examples/file-upload-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "gauge-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Gauge component showing core functionality.",
    slug: "gauge",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/gauge",
    registryDependencies: ["gauge"],
    files: [
      {
        path: "components/examples/gauge-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "key-value-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Key Value component showing core functionality.",
    slug: "key-value",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/key-value",
    registryDependencies: ["key-value"],
    files: [
      {
        path: "components/examples/key-value-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "mention-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Mention component showing core functionality.",
    slug: "mention",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/mention",
    registryDependencies: ["mention"],
    files: [
      {
        path: "components/examples/mention-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "phone-input-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Phone Input component showing core functionality.",
    slug: "phone-input",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/phone-input",
    registryDependencies: ["phone-input"],
    files: [
      {
        path: "components/examples/phone-input-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "prompt-library-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Prompt Library component showing core functionality.",
    slug: "prompt-library",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.cult-ui.com/docs/components/prompt-library",
    registryDependencies: ["prompt-library"],
    files: [
      {
        path: "components/examples/prompt-library-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["overlay"],
  },
  {
    name: "qr-code-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Qr Code component showing core functionality.",
    slug: "qr-code",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/qr-code",
    registryDependencies: ["qr-code"],
    files: [
      {
        path: "components/examples/qr-code-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "segmented-input-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Segmented Input component showing core functionality.",
    slug: "segmented-input",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/segmented-input",
    registryDependencies: ["segmented-input"],
    files: [
      {
        path: "components/examples/segmented-input-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "swap-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Swap component showing core functionality.",
    slug: "swap",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/swap",
    registryDependencies: ["swap"],
    files: [
      {
        path: "components/examples/swap-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["actions"],
  },
  {
    name: "tags-input-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Tags Input component showing core functionality.",
    slug: "tags-input",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/tags-input",
    registryDependencies: ["tags-input"],
    files: [
      {
        path: "components/examples/tags-input-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "terminal-animation-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Terminal Animation component showing core functionality.",
    slug: "terminal-animation",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.cult-ui.com/docs/components/terminal-animation",
    registryDependencies: ["terminal-animation"],
    files: [
      {
        path: "components/examples/terminal-animation-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["effects"],
  },
  {
    name: "timeline-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Timeline component showing core functionality.",
    slug: "timeline",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    height: "tall",
    upstreamUrl: "https://www.diceui.com/docs/components/radix/timeline",
    registryDependencies: ["timeline"],
    files: [
      {
        path: "components/examples/timeline-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "tour-default",
    type: "registry:example",
    title: "Default",
    description: "Default example for Tour component showing core functionality.",
    slug: "tour",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.diceui.com/docs/components/radix/tour",
    registryDependencies: ["tour"],
    files: [
      {
        path: "components/examples/tour-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["overlay"],
  },
  {
    name: "ring-loader-default",
    type: "registry:example",
    title: "Default",
    description:
      "Three ring-loader sizes side by side demonstrating size scaling and color override via text-primary token class.",
    slug: "ring-loader",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://loading-ui.com",
    registryDependencies: ["ring-loader"],
    files: [
      {
        path: "components/examples/ring-loader-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "api-response-viewer-default",
    type: "registry:example",
    title: "Default",
    description:
      "Mock 200 OK response with JSON body, request headers, and DNS/connect/TTFB/download timing waterfall breakdown.",
    slug: "api-response-viewer",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/api-response-viewer",
    registryDependencies: ["api-response-viewer"],
    files: [
      {
        path: "components/examples/api-response-viewer-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["data", "display"],
  },
  {
    name: "env-editor-default",
    type: "registry:example",
    title: "Default",
    description:
      "Controlled environment variable editor with four pre-populated vars, masked values, and .env import/export support.",
    slug: "env-editor",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/env-editor",
    registryDependencies: ["env-editor"],
    files: [
      {
        path: "components/examples/env-editor-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "data"],
  },
  {
    name: "error-boundary-ui-default",
    type: "registry:example",
    title: "Default",
    description:
      "Dev-mode error fallback with mock TypeError, parsed stack trace, component stack, copy button, and retry action.",
    slug: "error-boundary-ui",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/error-boundary-ui",
    registryDependencies: ["error-boundary-ui"],
    files: [
      {
        path: "components/examples/error-boundary-ui-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "json-viewer-default",
    type: "registry:example",
    title: "Default",
    description:
      "Collapsible JSON tree with nested object, array, null, boolean, and number types, search enabled, copy-path on hover.",
    slug: "json-viewer",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/json-viewer",
    registryDependencies: ["json-viewer"],
    files: [
      {
        path: "components/examples/json-viewer-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["data", "display"],
  },
  {
    name: "og-image-explorer-default",
    type: "registry:example",
    title: "Default",
    description:
      "OG image audit grid with six sample routes across two categories, including one intentionally broken URL for error state.",
    slug: "og-image-explorer",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/og-image-explorer",
    registryDependencies: ["og-image-explorer"],
    files: [
      {
        path: "components/examples/og-image-explorer-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "pdf-utils-default",
    type: "registry:example",
    title: "Default",
    description:
      "Interactive PDF utility demo with file upload, metadata extraction, and page thumbnail grid generation using client-side PDF processing.",
    slug: "pdf-utils",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://www.tryelements.dev/docs/pdf/pdf-utils",
    registryDependencies: ["pdf-utils"],
    files: [
      {
        path: "components/examples/pdf-utils-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["data"],
  },
  {
    name: "pdf-viewer-default",
    type: "registry:example",
    title: "Default",
    description:
      "PDF viewer in single-page mode loading a remote sample document with zoom controls and page navigation toolbar.",
    slug: "pdf-viewer",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://www.tryelements.dev/docs/pdf/pdf-viewer",
    registryDependencies: ["pdf-viewer"],
    files: [
      {
        path: "components/examples/pdf-viewer-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "webhook-tester-default",
    type: "registry:example",
    title: "Default",
    description:
      "HTTP request builder pre-filled with JSONPlaceholder POST endpoint, editable headers and body, with live response display.",
    slug: "webhook-tester",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/webhook-tester",
    registryDependencies: ["webhook-tester"],
    files: [
      {
        path: "components/examples/webhook-tester-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms", "data"],
  },

  {
    name: "evil-area-chart-default",
    type: "registry:example",
    title: "Default",
    description: "Area chart tracking monthly revenue and expenses with gradient fill.",
    slug: "evil-area-chart",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://evilcharts.com/docs/components/area-chart",
    registryDependencies: ["evil-area-chart"],
    files: [
      {
        path: "components/examples/evil-area-chart-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["charts"],
  },
  {
    name: "evil-bar-chart-default",
    type: "registry:example",
    title: "Default",
    description: "Bar chart showing quarterly sales vs returns with grouped bars.",
    slug: "evil-bar-chart",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://evilcharts.com/docs/components/bar-chart",
    registryDependencies: ["evil-bar-chart"],
    files: [
      {
        path: "components/examples/evil-bar-chart-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["charts"],
  },
  {
    name: "evil-line-chart-default",
    type: "registry:example",
    title: "Default",
    description: "Line chart tracking weekly users and signups with monotone curves.",
    slug: "evil-line-chart",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://evilcharts.com/docs/components/line-chart",
    registryDependencies: ["evil-line-chart"],
    files: [
      {
        path: "components/examples/evil-line-chart-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["charts"],
  },
  {
    name: "evil-pie-chart-default",
    type: "registry:example",
    title: "Default",
    description: "Donut pie chart showing traffic channel distribution.",
    slug: "evil-pie-chart",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://evilcharts.com/docs/components/pie-chart",
    registryDependencies: ["evil-pie-chart"],
    files: [
      {
        path: "components/examples/evil-pie-chart-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["charts"],
  },
  {
    name: "evil-radar-chart-default",
    type: "registry:example",
    title: "Default",
    description: "Radar chart comparing frontend vs backend across six dimensions.",
    slug: "evil-radar-chart",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://evilcharts.com/docs/components/radar-chart",
    registryDependencies: ["evil-radar-chart"],
    files: [
      {
        path: "components/examples/evil-radar-chart-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["charts"],
  },
  {
    name: "evil-composed-chart-default",
    type: "registry:example",
    title: "Default",
    description: "Composed chart overlaying monthly order bars with avg value trend line.",
    slug: "evil-composed-chart",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://evilcharts.com/docs/components/composed-chart",
    registryDependencies: ["evil-composed-chart"],
    files: [
      {
        path: "components/examples/evil-composed-chart-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["charts"],
  },
  {
    name: "animated-shiny-button-default",
    type: "registry:example",
    title: "Default",
    description: "Shiny CTA button with rotating conic-gradient border and shimmer on hover.",
    slug: "animated-shiny-button",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    upstreamUrl: "https://www.eldoraui.site/docs/components/animated-shiny-button",
    registryDependencies: ["animated-shiny-button"],
    files: [
      {
        path: "components/examples/animated-shiny-button-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["actions", "effects"],
  },
  {
    name: "browser-default",
    type: "registry:example",
    title: "Default",
    description:
      "Interactive browser simulator with tabs, address bar, macOS chrome, and simulated loading.",
    slug: "browser",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://www.eldoraui.site/docs/components/browser",
    registryDependencies: ["browser"],
    files: [
      {
        path: "components/examples/browser-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },

  {
    name: "border-beam-default",
    type: "registry:example",
    title: "Default",
    description:
      "Animated border beam effect wrapping a card with gradient text, demonstrating continuous perimeter glow animation.",
    slug: "border-beam",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://magicui.design/docs/components/border-beam",
    registryDependencies: ["border-beam"],
    files: [
      {
        path: "components/examples/border-beam-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["effects"],
  },
  {
    name: "bottom-navigation-default",
    type: "registry:example",
    title: "Default",
    description:
      "Mobile bottom navigation bar with five icon+label items, safe-area support, and active state highlighting.",
    slug: "bottom-navigation",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://shark.vini.one/docs/components/bottom-navigation",
    registryDependencies: ["bottom-navigation"],
    files: [
      {
        path: "components/examples/bottom-navigation-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["navigation"],
  },
  {
    name: "commit-graph-default",
    type: "registry:example",
    title: "Default",
    description:
      "Topological git commit graph with branching, merging, tags, refs, and interactive commit detail popovers.",
    slug: "commit-graph",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://ui.justinlevine.me/docs/components/commit-graph",
    registryDependencies: ["commit-graph"],
    files: [
      {
        path: "components/examples/commit-graph-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display", "data"],
  },
  {
    name: "empty-state-marquee",
    type: "registry:example",
    title: "Marquee",
    description:
      "Empty state with animated vertical marquee backdrop showing placeholder project items and two action buttons.",
    slug: "empty",
    variant: "marquee",
    isDefault: false,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://shadcnui-blocks.com/block/empty-state-04",
    registryDependencies: ["empty", "marquee", "button"],
    files: [
      {
        path: "components/examples/empty-state-marquee.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "command-popover-default",
    type: "registry:example",
    title: "Popover",
    description:
      "Command palette embedded in a popover with searchable contact list, icons, and description subtext per item.",
    slug: "command",
    variant: "popover",
    isDefault: false,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.shadcnblocks.com/component/command/command-popover-5",
    registryDependencies: ["command", "popover", "button"],
    files: [
      {
        path: "components/examples/command-popover-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["overlay"],
  },
  {
    name: "data-table-draggable",
    type: "registry:example",
    title: "Draggable Columns",
    description:
      "Data table with drag-and-drop column reordering using DnD Kit, sorting toggles, and currency formatting.",
    slug: "data-table",
    variant: "draggable",
    isDefault: false,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://shadcnstudio.com/docs/components/data-table",
    registryDependencies: ["table", "button"],
    files: [
      {
        path: "components/examples/data-table-draggable.tsx",
        type: "registry:example",
      },
    ],
    categories: ["data"],
  },
  {
    name: "data-table-expandable",
    type: "registry:example",
    title: "Expandable Rows",
    description:
      "Data table with expandable sub-rows showing nested team member details, row selection, and budget formatting.",
    slug: "data-table",
    variant: "expandable",
    isDefault: false,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://shadcnstudio.com/docs/components/data-table",
    registryDependencies: ["table", "button", "checkbox"],
    files: [
      {
        path: "components/examples/data-table-expandable.tsx",
        type: "registry:example",
      },
    ],
    categories: ["data"],
  },
  {
    name: "breadcrumb-icons",
    type: "registry:example",
    title: "Icons",
    description:
      "Breadcrumb with folder and file icons on every item, distinguishing parent directories from the current page.",
    slug: "breadcrumb",
    variant: "icons",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://www.shadcnblocks.com/components/breadcrumb",
    registryDependencies: ["breadcrumb"],
    files: [
      {
        path: "components/examples/breadcrumb-icons.tsx",
        type: "registry:example",
      },
    ],
    categories: ["navigation"],
  },
  {
    name: "breadcrumb-bordered",
    type: "registry:example",
    title: "Bordered",
    description:
      "Breadcrumb wrapped in a rounded bordered container with padding, creating a pill-style navigation element.",
    slug: "breadcrumb",
    variant: "bordered",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://www.shadcnblocks.com/components/breadcrumb",
    registryDependencies: ["breadcrumb"],
    files: [
      {
        path: "components/examples/breadcrumb-bordered.tsx",
        type: "registry:example",
      },
    ],
    categories: ["navigation"],
  },
  {
    name: "breadcrumb-bullet",
    type: "registry:example",
    title: "Bullet",
    description:
      "Breadcrumb with bullet dot separators instead of the default chevron, providing a compact visual alternative.",
    slug: "breadcrumb",
    variant: "bullet",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://www.shadcnblocks.com/components/breadcrumb",
    registryDependencies: ["breadcrumb"],
    files: [
      {
        path: "components/examples/breadcrumb-bullet.tsx",
        type: "registry:example",
      },
    ],
    categories: ["navigation"],
  },
  {
    name: "breadcrumb-slash",
    type: "registry:example",
    title: "Slash",
    description:
      "Breadcrumb with slash icon separators using the Lucide Slash icon for a traditional path-style appearance.",
    slug: "breadcrumb",
    variant: "slash",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://www.shadcnblocks.com/components/breadcrumb",
    registryDependencies: ["breadcrumb"],
    files: [
      {
        path: "components/examples/breadcrumb-slash.tsx",
        type: "registry:example",
      },
    ],
    categories: ["navigation"],
  },
  {
    name: "breadcrumb-select",
    type: "registry:example",
    title: "Select",
    description:
      "Breadcrumb with a Select dropdown for path segment navigation, allowing users to switch between sections inline.",
    slug: "breadcrumb",
    variant: "select",
    isDefault: false,
    isFlagged: false,
    upstreamUrl: "https://www.shadcnblocks.com/components/breadcrumb",
    registryDependencies: ["breadcrumb", "select"],
    files: [
      {
        path: "components/examples/breadcrumb-select.tsx",
        type: "registry:example",
      },
    ],
    categories: ["navigation"],
  },
  // ── ReUI compositions ──────────────────────────────────────────────
  {
    name: "c-button-39",
    type: "registry:example",
    title: "Button with unread badge",
    description:
      "Outline button with mail icon and destructive badge showing unread count, from ReUI registry.",
    slug: "reui-badge",
    variant: "button-unread",
    isDefault: true,
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "reui-badge"],
    files: [{ path: "components/examples/c-button-39.tsx", type: "registry:example" }],
    categories: ["actions"],
  },
  {
    name: "c-button-48",
    type: "registry:example",
    title: "Icon button with notification badge",
    description:
      "Square icon button with bell icon and compact destructive notification badge, from ReUI registry.",
    slug: "reui-badge",
    variant: "icon-notification",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "reui-badge"],
    files: [{ path: "components/examples/c-button-48.tsx", type: "registry:example" }],
    categories: ["actions"],
  },
  {
    name: "c-button-group-47",
    type: "registry:example",
    title: "Review actions split button",
    description:
      "Split button group with approve action and dropdown for conditional approval and rejection.",
    slug: "button-group",
    variant: "reui-review-actions",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "button-group", "dropdown-menu"],
    files: [
      {
        path: "components/examples/c-button-group-47.tsx",
        type: "registry:example",
      },
    ],
    categories: ["actions"],
  },
  {
    name: "c-button-group-53",
    type: "registry:example",
    title: "Publish controls with split button",
    description:
      "Toolbar with avatar group, preview button, split publish dropdown, and overflow menu.",
    slug: "button-group",
    variant: "reui-publish-controls",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["avatar", "button", "button-group", "dropdown-menu", "separator"],
    files: [
      {
        path: "components/examples/c-button-group-53.tsx",
        type: "registry:example",
      },
    ],
    categories: ["actions"],
  },
  {
    name: "c-calendar-4",
    type: "registry:example",
    title: "Multiple day selection",
    description:
      "Calendar demonstrating multi-day selection mode with pre-selected dates, from ReUI registry.",
    slug: "calendar",
    variant: "reui-multiple",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["calendar", "card"],
    files: [
      {
        path: "components/examples/c-calendar-4.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "c-calendar-10",
    type: "registry:example",
    title: "Calendar with week numbers",
    description:
      "Calendar displaying ISO week numbers alongside each row using custom WeekNumber component.",
    slug: "calendar",
    variant: "reui-week-numbers",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["calendar", "card"],
    files: [
      {
        path: "components/examples/c-calendar-10.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "c-calendar-17",
    type: "registry:example",
    title: "Calendar with pricing",
    description:
      "Calendar with per-day dynamic pricing using custom DayButton, prices under $100 highlighted green.",
    slug: "calendar",
    variant: "reui-pricing",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["calendar"],
    files: [
      {
        path: "components/examples/c-calendar-17.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "c-calendar-28",
    type: "registry:example",
    title: "Date picker with presets",
    description:
      "Popover date picker with sidebar preset buttons (Today, Yesterday, Last week, etc.) and calendar.",
    slug: "calendar",
    variant: "reui-date-picker-presets",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "calendar", "card", "popover"],
    files: [
      {
        path: "components/examples/c-calendar-28.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "c-calendar-29",
    type: "registry:example",
    title: "Range date picker with presets",
    description: "Popover date range picker with 8 preset ranges and dual-mode calendar selection.",
    slug: "calendar",
    variant: "reui-range-presets",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "calendar", "card", "popover"],
    files: [
      {
        path: "components/examples/c-calendar-29.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "c-card-5",
    type: "registry:example",
    title: "Card with link",
    description:
      "Compact help card with title, descriptive text, and link button with external link icon.",
    slug: "card",
    variant: "reui-with-link",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "card"],
    files: [{ path: "components/examples/c-card-5.tsx", type: "registry:example" }],
    categories: ["display"],
  },
  {
    name: "c-card-13",
    type: "registry:example",
    title: "Expandable billing usage card",
    description:
      "Billing card with credit usage progress bar, collapsible line items, and gradient fade toggle.",
    slug: "card",
    variant: "reui-expandable-billing",
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "card", "progress"],
    files: [{ path: "components/examples/c-card-13.tsx", type: "registry:example" }],
    categories: ["display"],
  },
  {
    name: "c-card-15",
    type: "registry:example",
    title: "Stat card with trend and overflow menu",
    description:
      "Revenue stat card with trend badge, delta percentage, comparison, and dropdown settings menu.",
    slug: "card",
    variant: "reui-stat-trend",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["reui-badge", "button", "card", "dropdown-menu", "separator"],
    files: [{ path: "components/examples/c-card-15.tsx", type: "registry:example" }],
    categories: ["display"],
  },
  {
    name: "c-card-18",
    type: "registry:example",
    title: "Card with header label and link",
    description:
      "Documentation card with icon-labeled header section, descriptive text, and inline link.",
    slug: "card",
    variant: "reui-header-label",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["card"],
    files: [{ path: "components/examples/c-card-18.tsx", type: "registry:example" }],
    categories: ["display"],
  },
  {
    name: "c-collapsible-4",
    type: "registry:example",
    title: "Collapsible card with bottom trigger",
    description:
      "Billing summary card with collapsible line items expanded by centered chevron button at bottom.",
    slug: "collapsible",
    variant: "reui-bottom-trigger",
    isFlagged: false,
    span: 1,
    height: "tall",
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "card", "collapsible", "progress"],
    files: [
      {
        path: "components/examples/c-collapsible-4.tsx",
        type: "registry:example",
      },
    ],
    categories: ["display"],
  },
  {
    name: "c-collapsible-5",
    type: "registry:example",
    title: "Collapsible form fields",
    description:
      "Unit pricing form with base price input and collapsible tax/discount fields toggled by settings button.",
    slug: "collapsible",
    variant: "reui-form-fields",
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "card", "collapsible", "field", "input-group"],
    files: [
      {
        path: "components/examples/c-collapsible-5.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "c-combobox-19",
    type: "registry:example",
    title: "Multi-select combobox with user tags",
    description:
      "Combobox with avatar-decorated chips, searchable dropdown, removable selections, and member info.",
    slug: "combobox",
    variant: "reui-multi-select-users",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["avatar", "combobox", "field", "item"],
    files: [
      {
        path: "components/examples/c-combobox-19.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "c-command-7",
    type: "registry:example",
    title: "Action palette with keyboard shortcuts",
    description:
      "Command dialog with grouped actions (Create, Navigate, System) and keyboard shortcut indicators.",
    slug: "command",
    variant: "reui-action-palette",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "command"],
    files: [{ path: "components/examples/c-command-7.tsx", type: "registry:example" }],
    categories: ["overlay"],
  },
  {
    name: "c-command-8",
    type: "registry:example",
    title: "Command with recent and favorites",
    description:
      "Search dialog with starred favorites, timestamped recent pages, and quick links for navigation.",
    slug: "command",
    variant: "reui-recent-favorites",
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://reui.io/components",
    registryDependencies: ["button", "command"],
    files: [{ path: "components/examples/c-command-8.tsx", type: "registry:example" }],
    categories: ["overlay"],
  },
  {
    name: "floating-panel-default",
    type: "registry:example",
    title: "Default",
    description:
      "Floating panel with draggable header, scrollable body, minimize/maximize controls, and footer actions.",
    slug: "floating-panel",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://shark.vini.one/docs/components/floating-panel",
    registryDependencies: ["floating-panel", "button"],
    files: [
      {
        path: "components/examples/floating-panel-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["overlay"],
  },
  {
    name: "signature-pad-default",
    type: "registry:example",
    title: "Default",
    description:
      "Canvas signature pad with guide line, clear button, and descriptive label for hand-drawn input capture.",
    slug: "signature-pad",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    height: "tall",
    upstreamUrl: "https://shark.vini.one/docs/components/signature-pad",
    registryDependencies: ["signature-pad"],
    files: [
      {
        path: "components/examples/signature-pad-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "download-trigger-default",
    type: "registry:example",
    title: "Default",
    description:
      "Download trigger with JSON file export and async text generation demonstrating sync and async data sources.",
    slug: "download-trigger",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 1,
    upstreamUrl: "https://shark.vini.one/docs/utilities/download-trigger",
    registryDependencies: ["download-trigger", "button"],
    files: [
      {
        path: "components/examples/download-trigger-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["actions"],
  },
  {
    name: "liquid-metal-button-default",
    type: "registry:example",
    title: "Default",
    description:
      "WebGL liquid metal button in text and icon view modes with 3D shader animation and ripple click effects.",
    slug: "liquid-metal-button",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://www.jolyui.dev/docs/components/buttons/liquid-metal-button",
    registryDependencies: ["liquid-metal-button"],
    files: [
      {
        path: "components/examples/liquid-metal-button-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["buttons"],
  },
  {
    name: "snail-timer-default",
    type: "registry:example",
    title: "Default",
    description:
      "Animated snail countdown timer with start/pause controls, dust trail animation, and configurable duration.",
    slug: "snail-timer",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://www.uicapsule.com",
    registryDependencies: ["snail-timer", "button"],
    files: [
      {
        path: "components/examples/snail-timer-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["feedback"],
  },
  {
    name: "creatable-combobox-default",
    type: "registry:example",
    title: "Default",
    description:
      "Combobox with autocomplete filtering and dynamic item creation for picking or adding new fruit entries.",
    slug: "creatable-combobox",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 2,
    upstreamUrl: "https://flowkit-ui.vzkiss.com/docs/components/creatable-combobox",
    registryDependencies: ["creatable-combobox", "combobox"],
    files: [
      {
        path: "components/examples/creatable-combobox-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["forms"],
  },
  {
    name: "data-table-filter-default",
    type: "registry:example",
    title: "Default",
    description:
      "Linear-style filter bar with text, option, and number columns. Filter pills show subject, operator, and value. Live filtering across an employee table.",
    slug: "data-table-filter",
    variant: "default",
    isDefault: true,
    isFlagged: false,
    span: 3,
    height: "tall",
    upstreamUrl: "https://ui.bazza.dev/docs/data-table-filter",
    registryDependencies: ["data-table-filter"],
    files: [
      {
        path: "components/examples/data-table-filter-default.tsx",
        type: "registry:example",
      },
    ],
    categories: ["data"],
  },
]);
