/**
 * Primitive registry. One entry per file in `src/components/ui/`.
 *
 * Edit by hand. The build script reads this and validates every name.
 * `registryDependencies` lists OTHER primitives a primitive composes
 * (for example, `alert-dialog` depends on `button`).
 *
 * Each item maps to `https://ui.shadcn.com/docs/components/<name>`.
 */
import { defineItems } from "@/lib/registry-schema";

export const items = defineItems([
  {
    name: "accordion",
    type: "registry:ui",
    title: "Accordion",
    description:
      "Vertically stacked set of interactive headings, each revealing a section of content.",
    files: [{ path: "components/ui/accordion.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/accordion",
    categories: ["disclosure"],
  },
  {
    name: "alert",
    type: "registry:ui",
    title: "Alert",
    description: "Callout for user attention with optional icon, title, description, and action.",
    files: [{ path: "components/ui/alert.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/alert",
    categories: ["feedback"],
  },
  {
    name: "alert-dialog",
    type: "registry:ui",
    title: "Alert Dialog",
    description:
      "Modal dialog that interrupts the user with critical content and expects a response.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/alert-dialog.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/alert-dialog",
    categories: ["overlay", "feedback"],
  },
  {
    name: "aspect-ratio",
    type: "registry:ui",
    title: "Aspect Ratio",
    description: "Constrains content to a specified ratio.",
    files: [{ path: "components/ui/aspect-ratio.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/aspect-ratio",
    categories: ["layout"],
  },
  {
    name: "avatar",
    type: "registry:ui",
    title: "Avatar",
    description: "Image element with a fallback, plus group, badge, and count subcomponents.",
    files: [{ path: "components/ui/avatar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    categories: ["display"],
  },
  {
    name: "badge",
    type: "registry:ui",
    title: "Badge",
    description:
      "Small label component for status, counts, and tags. Variants and asChild supported.",
    files: [{ path: "components/ui/badge.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    categories: ["display"],
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    title: "Breadcrumb",
    description: "Hierarchical navigation showing the path to the current resource.",
    files: [{ path: "components/ui/breadcrumb.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/breadcrumb",
    categories: ["navigation"],
  },
  {
    name: "button",
    type: "registry:ui",
    title: "Button",
    description:
      "Primary action element. Variants: default, outline, secondary, ghost, destructive, link. Sizes: xs, sm, default, lg, icon, icon-xs, icon-sm, icon-lg.",
    files: [{ path: "components/ui/button.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/button",
    categories: ["actions", "forms"],
  },
  {
    name: "button-group",
    type: "registry:ui",
    title: "Button Group",
    description: "Container that groups related buttons with shared edges and consistent styling.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/button-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/button-group",
    categories: ["actions"],
  },
  {
    name: "calendar",
    type: "registry:ui",
    title: "Calendar",
    description:
      "Date picker calendar. Modes: single, range. Supports presets, time picker, week numbers, custom cell renderers.",
    files: [{ path: "components/ui/calendar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    categories: ["forms", "display"],
  },
  {
    name: "card",
    type: "registry:ui",
    title: "Card",
    description: "Surface with header, content, and footer slots. Size variants supported.",
    files: [{ path: "components/ui/card.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/card",
    categories: ["layout", "display"],
  },
  {
    name: "carousel",
    type: "registry:ui",
    title: "Carousel",
    description: "Slide-and-swipe carousel with motion built on Embla.",
    files: [{ path: "components/ui/carousel.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/carousel",
    categories: ["display"],
  },
  {
    name: "chart",
    type: "registry:ui",
    title: "Chart",
    description: "Recharts-backed chart primitives with shared tooltip, legend, config tokens.",
    files: [{ path: "components/ui/chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    categories: ["display", "data-viz"],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    title: "Checkbox",
    description: "Toggle between checked, unchecked, indeterminate states.",
    files: [{ path: "components/ui/checkbox.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/checkbox",
    categories: ["forms"],
  },
  {
    name: "collapsible",
    type: "registry:ui",
    title: "Collapsible",
    description: "Interactive component that expands and collapses a panel.",
    files: [{ path: "components/ui/collapsible.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/collapsible",
    categories: ["disclosure"],
  },
  {
    name: "combobox",
    type: "registry:ui",
    title: "Combobox",
    description:
      "Autocomplete input with a list of suggestions. Supports multi-select, groups, custom items.",
    registryDependencies: ["popover", "command"],
    files: [{ path: "components/ui/combobox.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/combobox",
    categories: ["forms"],
  },
  {
    name: "command",
    type: "registry:ui",
    title: "Command",
    description: "Command palette for search and quick actions, with shortcuts and groups.",
    registryDependencies: ["dialog"],
    files: [{ path: "components/ui/command.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/command",
    categories: ["navigation", "search"],
  },
  {
    name: "context-menu",
    type: "registry:ui",
    title: "Context Menu",
    description: "Menu of actions triggered by a right click.",
    files: [{ path: "components/ui/context-menu.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/context-menu",
    categories: ["overlay", "menu"],
  },
  {
    name: "dialog",
    type: "registry:ui",
    title: "Dialog",
    description: "Window overlaid on the primary window, rendering content underneath inert.",
    files: [{ path: "components/ui/dialog.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/dialog",
    categories: ["overlay"],
  },
  {
    name: "drawer",
    type: "registry:ui",
    title: "Drawer",
    description: "Edge-anchored drawer for React with vaul.",
    files: [{ path: "components/ui/drawer.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/drawer",
    categories: ["overlay"],
  },
  {
    name: "dropdown-menu",
    type: "registry:ui",
    title: "Dropdown Menu",
    description:
      "Menu of actions or functions triggered by a button. Submenus, checkboxes, radio groups, shortcuts.",
    files: [{ path: "components/ui/dropdown-menu.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/dropdown-menu",
    categories: ["overlay", "menu"],
  },
  {
    name: "empty",
    type: "registry:ui",
    title: "Empty",
    description:
      "Empty-state component with media, header, title, description, content, action slots.",
    files: [{ path: "components/ui/empty.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/empty",
    categories: ["feedback", "display"],
  },
  {
    name: "field",
    type: "registry:ui",
    title: "Field",
    description: "Composable form field wrapper: label, control, description, error.",
    registryDependencies: ["label"],
    files: [{ path: "components/ui/field.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/field",
    categories: ["forms"],
  },
  {
    name: "hover-card",
    type: "registry:ui",
    title: "Hover Card",
    description: "Preview content available behind a link on hover (sighted users only).",
    files: [{ path: "components/ui/hover-card.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/hover-card",
    categories: ["overlay"],
  },
  {
    name: "input",
    type: "registry:ui",
    title: "Input",
    description: "Text input. Supports type variants, disabled, invalid (aria-invalid), file.",
    files: [{ path: "components/ui/input.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/input",
    categories: ["forms"],
  },
  {
    name: "visually-hidden-input",
    type: "registry:ui",
    title: "Visually Hidden Input",
    description:
      "Hidden native input that mirrors a visible custom control's value/checked so the surrounding form picks it up. Used by composed primitives (key-value, phone-input).",
    files: [{ path: "components/ui/visually-hidden-input.tsx", type: "registry:ui" }],
    categories: ["forms"],
  },
  {
    name: "input-group",
    type: "registry:ui",
    title: "Input Group",
    description: "Composed input layout with addons, buttons, and helper content.",
    registryDependencies: ["input"],
    files: [{ path: "components/ui/input-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/input-group",
    categories: ["forms"],
  },
  {
    name: "input-otp",
    type: "registry:ui",
    title: "Input OTP",
    description:
      "One-time password input with copy-paste, separators, patterns. ALWAYS controlled — never use defaultValue (library bug).",
    files: [{ path: "components/ui/input-otp.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/input-otp",
    categories: ["forms"],
    deviations: [
      "Must use controlled value/onChange. Library renders both value and defaultValue on hidden input when defaultValue is set, triggering React error.",
    ],
  },
  {
    name: "item",
    type: "registry:ui",
    title: "Item",
    description: "Versatile list/row component with media, title, description, and actions slots.",
    files: [{ path: "components/ui/item.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/item",
    categories: ["display", "layout"],
  },
  {
    name: "kbd",
    type: "registry:ui",
    title: "Kbd",
    description: "Display textual keyboard input. Group multiple keys with KbdGroup.",
    files: [{ path: "components/ui/kbd.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/kbd",
    categories: ["display"],
  },
  {
    name: "label",
    type: "registry:ui",
    title: "Label",
    description: "Accessible label associated with form controls.",
    files: [{ path: "components/ui/label.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/label",
    categories: ["forms"],
  },
  {
    name: "menubar",
    type: "registry:ui",
    title: "Menubar",
    description:
      "Persistent menu common in desktop apps. Submenus, checkboxes, radio groups, shortcuts.",
    files: [{ path: "components/ui/menubar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/menubar",
    categories: ["navigation", "menu"],
  },
  {
    name: "native-select",
    type: "registry:ui",
    title: "Native Select",
    description: "Styled native HTML <select> element with consistent design system integration.",
    files: [{ path: "components/ui/native-select.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/native-select",
    categories: ["forms"],
  },
  {
    name: "navigation-menu",
    type: "registry:ui",
    title: "Navigation Menu",
    description: "Collection of links with optional dropdown panels for site navigation.",
    files: [{ path: "components/ui/navigation-menu.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/navigation-menu",
    categories: ["navigation"],
  },
  {
    name: "pagination",
    type: "registry:ui",
    title: "Pagination",
    description: "Page navigation with previous, next, and numbered links.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/pagination.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/pagination",
    categories: ["navigation"],
  },
  {
    name: "popover",
    type: "registry:ui",
    title: "Popover",
    description: "Rich content in a portal triggered by a button.",
    files: [{ path: "components/ui/popover.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/popover",
    categories: ["overlay"],
  },
  {
    name: "progress",
    type: "registry:ui",
    title: "Progress",
    description: "Progress bar showing completion of a task.",
    files: [{ path: "components/ui/progress.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/progress",
    categories: ["feedback"],
  },
  {
    name: "radio-group",
    type: "registry:ui",
    title: "Radio Group",
    description: "Set of checkable radio buttons; only one selected at a time.",
    files: [{ path: "components/ui/radio-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/radio-group",
    categories: ["forms"],
  },
  {
    name: "resizable",
    type: "registry:ui",
    title: "Resizable",
    description: "Accessible resizable panel groups with keyboard support.",
    files: [{ path: "components/ui/resizable.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/resizable",
    categories: ["layout"],
  },
  {
    name: "scroll-area",
    type: "registry:ui",
    title: "Scroll Area",
    description: "Augmented native scroll with custom cross-browser styling.",
    files: [{ path: "components/ui/scroll-area.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/scroll-area",
    categories: ["layout"],
  },
  {
    name: "select",
    type: "registry:ui",
    title: "Select",
    description: "Listbox-style select with groups, scrollable lists, and triggers.",
    files: [{ path: "components/ui/select.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/select",
    categories: ["forms"],
  },
  {
    name: "separator",
    type: "registry:ui",
    title: "Separator",
    description: "Visual or semantic divider between content.",
    files: [{ path: "components/ui/separator.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/separator",
    categories: ["layout"],
  },
  {
    name: "sheet",
    type: "registry:ui",
    title: "Sheet",
    description: "Edge-anchored panel extending Dialog for complementary content.",
    registryDependencies: ["dialog"],
    files: [{ path: "components/ui/sheet.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/sheet",
    categories: ["overlay"],
  },
  {
    name: "sidebar",
    type: "registry:ui",
    title: "Sidebar",
    description:
      "Composable themeable sidebar with provider, header, footer, content, menu, trigger, rail, inset, and collapsible behaviors.",
    registryDependencies: ["button", "tooltip", "sheet"],
    files: [{ path: "components/ui/sidebar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/sidebar",
    categories: ["layout", "navigation"],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    title: "Skeleton",
    description: "Loading-state placeholder.",
    files: [{ path: "components/ui/skeleton.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    categories: ["feedback"],
  },
  {
    name: "slider",
    type: "registry:ui",
    title: "Slider",
    description: "Range input. Single thumb, multiple thumbs, vertical orientation supported.",
    files: [{ path: "components/ui/slider.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/slider",
    categories: ["forms"],
  },
  {
    name: "sonner",
    type: "registry:ui",
    title: "Sonner",
    description: "Toast notifications. Types: default, success, info, warning, error, promise.",
    files: [{ path: "components/ui/sonner.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/sonner",
    categories: ["feedback"],
  },
  {
    name: "spinner",
    type: "registry:ui",
    title: "Spinner",
    description: "Loading indicator. Compose with Button, Badge, Input Group, Empty.",
    files: [{ path: "components/ui/spinner.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/spinner",
    categories: ["feedback"],
  },
  {
    name: "switch",
    type: "registry:ui",
    title: "Switch",
    description: "Toggle control: checked / unchecked. Sized variants supported.",
    files: [{ path: "components/ui/switch.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/switch",
    categories: ["forms"],
  },
  {
    name: "table",
    type: "registry:ui",
    title: "Table",
    description: "Responsive table with header, body, footer, caption.",
    files: [{ path: "components/ui/table.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/table",
    categories: ["display", "data"],
  },
  {
    name: "tabs",
    type: "registry:ui",
    title: "Tabs",
    description: "Layered sections of content displayed one panel at a time.",
    files: [{ path: "components/ui/tabs.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/tabs",
    categories: ["navigation", "disclosure"],
  },
  {
    name: "textarea",
    type: "registry:ui",
    title: "Textarea",
    description: "Multi-line text input.",
    files: [{ path: "components/ui/textarea.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/textarea",
    categories: ["forms"],
  },
  {
    name: "toggle",
    type: "registry:ui",
    title: "Toggle",
    description: "Two-state button (on/off). Variants and sizes.",
    files: [{ path: "components/ui/toggle.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/toggle",
    categories: ["actions"],
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    title: "Toggle Group",
    description: "Set of two-state buttons. Single/multiple selection, vertical, spacing prop.",
    registryDependencies: ["toggle"],
    files: [{ path: "components/ui/toggle-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/toggle-group",
    categories: ["actions"],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    title: "Tooltip",
    description: "Floating popup on focus or hover with descriptive text.",
    files: [{ path: "components/ui/tooltip.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/tooltip",
    categories: ["overlay"],
  },
  {
    name: "noise-background",
    type: "registry:ui",
    title: "Noise Background",
    description:
      "Animated gradient background with noise texture overlay, spring physics, adjustable speed, and optional backdrop blur.",
    files: [{ path: "components/ui/noise-background.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.aceternity.com/components/noise-background",
    categories: ["display", "effects"],
    proposedGroup: "effects",
  },
  {
    name: "stateful-button",
    type: "registry:ui",
    title: "Stateful Button",
    description:
      "Action button with built-in loading spinner and success check animation sequence driven by motion/react.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/stateful-button.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.aceternity.com/components/stateful-button",
    categories: ["actions", "effects"],
    proposedGroup: "buttons",
  },
  {
    name: "multi-step-loader",
    type: "registry:ui",
    title: "Multi Step Loader",
    description:
      "Full-screen loading overlay that cycles through a list of steps with animated check marks and progress indicators.",
    files: [{ path: "components/ui/multi-step-loader.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.aceternity.com/components/multi-step-loader",
    categories: ["feedback", "effects"],
    proposedGroup: "feedback",
  },
  {
    name: "separator-extended",
    type: "registry:ui",
    title: "Separator Extended",
    description:
      "Separator with variant styles: solid (default), dashed, dotted, and double. Supports horizontal and vertical orientation.",
    registryDependencies: ["separator"],
    files: [{ path: "components/ui/separator-extended.tsx", type: "registry:ui" }],
    upstreamUrl: "https://basecn.dev/docs/components/separator-extended",
    categories: ["layout"],
    proposedGroup: "layout",
  },
  {
    name: "card-styles",
    type: "registry:ui",
    title: "Card Styles",
    description:
      "Creative card style variants: retro shadow, line borders, hatched pattern, aurora glow, tilted layer, and stacked depth.",
    registryDependencies: ["card"],
    files: [{ path: "components/ui/card-styles.tsx", type: "registry:ui" }],
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    categories: ["display", "layout"],
    proposedGroup: "display",
  },
  {
    name: "autocomplete",
    type: "registry:ui",
    title: "Autocomplete",
    description:
      "Input that suggests options as you type. Inline autofill, auto-highlight, async search, groups, clear button, and trigger toggle.",
    registryDependencies: ["scroll-area"],
    files: [{ path: "components/ui/autocomplete.tsx", type: "registry:ui" }],
    upstreamUrl: "https://coss.com/ui/docs/components/autocomplete",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "action-bar",
    type: "registry:ui",
    title: "Action Bar",
    description:
      "Floating toolbar that appears on selection with keyboard navigation, item actions, close button, and separator. Portal-mounted with configurable position.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/action-bar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/action-bar",
    categories: ["actions", "overlay"],
    proposedGroup: "actions",
  },
  {
    name: "banner",
    type: "registry:ui",
    title: "Banner",
    description:
      "Dismissible notification banner with variant styles, icon, action button, and close. Supports top/bottom layout.",
    files: [{ path: "components/ui/banner.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/banner",
    categories: ["feedback"],
    proposedGroup: "feedback",
  },
  {
    name: "border-beam-button",
    type: "registry:ui",
    title: "Border Beam Button",
    description:
      "Button wrapped with animated beam border effect. Standard and icon-only variants.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/border-beam-button.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.cult-ui.com/docs/components/border-beam-button",
    categories: ["actions", "effects"],
    proposedGroup: "buttons",
  },
  {
    name: "circular-progress",
    type: "registry:ui",
    title: "Circular Progress",
    description:
      "SVG-based circular progress indicator with configurable size, thickness, and value display.",
    files: [{ path: "components/ui/circular-progress.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/circular-progress",
    categories: ["feedback", "display"],
    proposedGroup: "feedback",
  },
  {
    name: "color-picker",
    type: "registry:ui",
    title: "Color Picker",
    description:
      "HSL color area picker with hue slider, hex/HSL input, and preset swatches in a popover.",
    registryDependencies: ["button", "input", "label", "popover"],
    files: [{ path: "components/ui/color-picker.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/color-picker",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "color-swatch",
    type: "registry:ui",
    title: "Color Swatch",
    description:
      "Color preview swatch with configurable size, radius, and optional checkered background for transparency.",
    files: [{ path: "components/ui/color-swatch.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/color-swatch",
    categories: ["display"],
    proposedGroup: "display",
  },
  {
    name: "cropper",
    type: "registry:ui",
    title: "Cropper",
    description:
      "Image cropper with zoom, rotation, aspect ratio lock, and crop area selection. Touch and keyboard support.",
    files: [{ path: "components/ui/cropper.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/cropper",
    categories: ["forms", "display"],
    proposedGroup: "forms",
  },
  {
    name: "data-grid",
    type: "registry:ui",
    title: "Data Grid",
    description:
      "High-performance editable spreadsheet with virtualization, 9 cell types, clipboard, undo/redo, search, sorting, and column management.",
    registryDependencies: [
      "button",
      "checkbox",
      "command",
      "context-menu",
      "dialog",
      "dropdown-menu",
      "input",
      "popover",
      "select",
      "separator",
      "table",
      "tooltip",
    ],
    files: [{ path: "components/ui/data-grid.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/data-grid",
    categories: ["data", "forms"],
    proposedGroup: "data",
  },
  {
    name: "data-table",
    type: "registry:ui",
    title: "Data Table",
    description:
      "Feature-rich data table with advanced filtering, URL state sync, multi-column sorting, pagination, column visibility, row selection, and action bar.",
    registryDependencies: [
      "button",
      "badge",
      "calendar",
      "checkbox",
      "command",
      "dialog",
      "dropdown-menu",
      "input",
      "popover",
      "select",
      "separator",
      "skeleton",
      "slider",
      "table",
      "tooltip",
    ],
    files: [{ path: "components/ui/data-table.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/data-table",
    categories: ["data", "display"],
    proposedGroup: "data",
  },
  {
    name: "file-upload",
    type: "registry:ui",
    title: "File Upload",
    description:
      "Drag-and-drop file upload with progress tracking, file type validation, size limits, and preview thumbnails.",
    files: [{ path: "components/ui/file-upload.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/file-upload",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "gauge",
    type: "registry:ui",
    title: "Gauge",
    description:
      "SVG gauge/meter component with configurable min/max, segments, labels, and needle indicator.",
    files: [{ path: "components/ui/gauge.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/gauge",
    categories: ["display", "feedback"],
    proposedGroup: "display",
  },
  {
    name: "key-value",
    type: "registry:ui",
    title: "Key Value",
    description:
      "Editable key-value pair input with add/remove/reorder, validation, and clipboard support.",
    files: [{ path: "components/ui/key-value.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/key-value",
    categories: ["display", "forms"],
    proposedGroup: "display",
  },
  {
    name: "mention",
    type: "registry:ui",
    title: "Mention",
    description:
      "Text input with @mention autocomplete suggestions triggered by a configurable character.",
    files: [{ path: "components/ui/mention.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/mention",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "phone-input",
    type: "registry:ui",
    title: "Phone Input",
    description:
      "International phone number input with country code selector, flag display, and format validation.",
    files: [{ path: "components/ui/phone-input.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/phone-input",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "prompt-library",
    type: "registry:ui",
    title: "Prompt Library",
    description:
      "AI prompt template library in a popover with search, categories, hover preview, and custom prompt creation.",
    registryDependencies: [
      "button",
      "command",
      "dialog",
      "hover-card",
      "input",
      "popover",
      "textarea",
    ],
    files: [{ path: "components/ui/prompt-library.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.cult-ui.com/docs/components/prompt-library",
    categories: ["overlay", "forms"],
    proposedGroup: "overlay",
  },
  {
    name: "qr-code",
    type: "registry:ui",
    title: "QR Code",
    description:
      "QR code generator with customizable size, error correction, colors, and optional logo overlay.",
    files: [{ path: "components/ui/qr-code.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/qr-code",
    categories: ["display"],
    proposedGroup: "display",
  },
  {
    name: "segmented-input",
    type: "registry:ui",
    title: "Segmented Input",
    description:
      "Multi-segment input (date, time, code) with individual segment focus, keyboard navigation, and validation.",
    files: [{ path: "components/ui/segmented-input.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/segmented-input",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "swap",
    type: "registry:ui",
    title: "Swap",
    description: "Animated toggle between two content states with configurable transition effects.",
    files: [{ path: "components/ui/swap.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/swap",
    categories: ["actions", "effects"],
    proposedGroup: "actions",
  },
  {
    name: "tags-input",
    type: "registry:ui",
    title: "Tags Input",
    description:
      "Input field for adding and removing tags/chips with keyboard support and validation.",
    files: [{ path: "components/ui/tags-input.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/tags-input",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "terminal-animation",
    type: "registry:ui",
    title: "Terminal Animation",
    description:
      "Animated terminal/CLI output with typing effect, tab navigation, command bar, blinking cursor, and line-by-line reveal.",
    files: [{ path: "components/ui/terminal-animation.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.cult-ui.com/docs/components/terminal-animation",
    categories: ["display", "effects"],
    proposedGroup: "effects",
  },
  {
    name: "timeline",
    type: "registry:ui",
    title: "Timeline",
    description:
      "Vertical or horizontal timeline with active step tracking, connector lines, and customizable content per step.",
    files: [{ path: "components/ui/timeline.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/timeline",
    categories: ["display"],
    proposedGroup: "display",
  },
  {
    name: "tour",
    type: "registry:ui",
    title: "Tour",
    description:
      "Multi-step guided tour overlay with spotlight highlighting, step navigation, keyboard support, and scroll-to-target.",
    files: [{ path: "components/ui/tour.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.diceui.com/docs/components/radix/tour",
    categories: ["overlay", "navigation"],
    proposedGroup: "overlay",
  },
  {
    name: "ring-loader",
    type: "registry:ui",
    title: "Ring Loader",
    description:
      "Lightweight SVG spinning ring indicator with configurable size and speed via --duration CSS variable, uses currentColor.",
    files: [{ path: "components/ui/ring-loader.tsx", type: "registry:ui" }],
    upstreamUrl: "https://loading-ui.com",
    categories: ["feedback"],
    proposedGroup: "feedback",
  },
  {
    name: "api-response-viewer",
    type: "registry:ui",
    title: "API Response Viewer",
    description:
      "Tabbed HTTP response inspector with status badge, collapsible JSON body, headers table, and timing waterfall breakdown.",
    registryDependencies: ["button", "tabs"],
    files: [{ path: "components/ui/api-response-viewer.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/api-response-viewer",
    categories: ["data", "display"],
    proposedGroup: "devtools",
  },
  {
    name: "env-editor",
    type: "registry:ui",
    title: "Env Editor",
    description:
      "Key-value grid editor for environment variables with masked values, add/remove rows, and .env file import/export.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/env-editor.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/env-editor",
    categories: ["forms", "data"],
    proposedGroup: "devtools",
  },
  {
    name: "error-boundary-ui",
    type: "registry:ui",
    title: "Error Boundary UI",
    description:
      "Error fallback display with stack trace parsing, copy-to-clipboard, retry button, and dev/prod verbosity modes.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/error-boundary-ui.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/error-boundary-ui",
    categories: ["feedback"],
    proposedGroup: "devtools",
  },
  {
    name: "json-viewer",
    type: "registry:ui",
    title: "JSON Viewer",
    description:
      "Collapsible JSON tree with syntax-highlighted types, configurable depth, search filter, and copy-path-on-hover.",
    registryDependencies: ["button", "input"],
    files: [{ path: "components/ui/json-viewer.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/json-viewer",
    categories: ["data", "display"],
    proposedGroup: "devtools",
  },
  {
    name: "og-image-explorer",
    type: "registry:ui",
    title: "OG Image Explorer",
    description:
      "Visual gallery grid for auditing Open Graph images across app routes, with status borders and category grouping.",
    registryDependencies: ["og-category-section", "og-image-card"],
    files: [{ path: "components/ui/og-image-explorer.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/og-image-explorer",
    categories: ["display"],
    proposedGroup: "devtools",
  },
  {
    name: "og-category-section",
    type: "registry:ui",
    title: "OG Category Section",
    description:
      "Internal sub-component of OG Image Explorer: collapsible category group with expand/collapse and item count.",
    registryDependencies: ["og-image-card"],
    files: [{ path: "components/ui/og-category-section.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/og-image-explorer",
    categories: ["display"],
    proposedGroup: "devtools",
  },
  {
    name: "og-image-card",
    type: "registry:ui",
    title: "OG Image Card",
    description:
      "Internal sub-component of OG Image Explorer: single OG image preview card with load/error status border indicator.",
    files: [{ path: "components/ui/og-image-card.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/og-image-explorer",
    categories: ["display"],
    proposedGroup: "devtools",
  },
  {
    name: "pdf-utils",
    type: "registry:ui",
    title: "PDF Utils",
    description:
      "Client-side PDF utility library: extract metadata, screenshot pages, search text, generate thumbnails, and split page ranges.",
    files: [{ path: "components/ui/pdf-utils.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/pdf/pdf-utils",
    categories: ["data"],
    proposedGroup: "pdf",
  },
  {
    name: "pdf-viewer",
    type: "registry:ui",
    title: "PDF Viewer",
    description:
      "Full-featured PDF viewer with single-page, continuous-scroll, and book layout modes, zoom controls, and page navigation.",
    registryDependencies: ["pdf-utils", "button", "input"],
    files: [{ path: "components/ui/pdf-viewer.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/pdf/pdf-viewer",
    categories: ["display"],
    proposedGroup: "pdf",
  },
  {
    name: "webhook-tester",
    type: "registry:ui",
    title: "Webhook Tester",
    description:
      "HTTP request builder with method selector, URL input, headers editor, JSON body, and color-coded response display.",
    registryDependencies: ["button", "input", "native-select", "textarea"],
    files: [{ path: "components/ui/webhook-tester.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.tryelements.dev/docs/devtools/webhook-tester",
    categories: ["forms", "data"],
    proposedGroup: "devtools",
  },

  {
    name: "evil-area-chart",
    type: "registry:ui",
    title: "Evil Area Chart",
    description:
      "Feature-rich area chart with gradient fill, animated skeleton, brush zoom, and glow support.",
    files: [{ path: "components/ui/evil-area-chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://evilcharts.com/docs/components/area-chart",
    categories: ["charts"],
    proposedGroup: "charts",
  },
  {
    name: "evil-bar-chart",
    type: "registry:ui",
    title: "Evil Bar Chart",
    description:
      "Feature-rich bar chart with stacked, grouped, percent variants, animated skeleton, and glow effects.",
    files: [{ path: "components/ui/evil-bar-chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://evilcharts.com/docs/components/bar-chart",
    categories: ["charts"],
    proposedGroup: "charts",
  },
  {
    name: "evil-line-chart",
    type: "registry:ui",
    title: "Evil Line Chart",
    description:
      "Feature-rich line chart with monotone, step, linear curves, animated skeleton, and glow effects.",
    files: [{ path: "components/ui/evil-line-chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://evilcharts.com/docs/components/line-chart",
    categories: ["charts"],
    proposedGroup: "charts",
  },
  {
    name: "evil-pie-chart",
    type: "registry:ui",
    title: "Evil Pie Chart",
    description:
      "Feature-rich pie and donut chart with configurable radius, padding angle, and animated skeleton.",
    files: [{ path: "components/ui/evil-pie-chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://evilcharts.com/docs/components/pie-chart",
    categories: ["charts"],
    proposedGroup: "charts",
  },
  {
    name: "evil-radar-chart",
    type: "registry:ui",
    title: "Evil Radar Chart",
    description:
      "Feature-rich radar chart with filled, lines variants, polygon grid, radial gradients, and glow effects.",
    files: [{ path: "components/ui/evil-radar-chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://evilcharts.com/docs/components/radar-chart",
    categories: ["charts"],
    proposedGroup: "charts",
  },
  {
    name: "evil-composed-chart",
    type: "registry:ui",
    title: "Evil Composed Chart",
    description:
      "Feature-rich composed chart overlaying bars and lines on shared axis with glow effects and skeleton.",
    files: [{ path: "components/ui/evil-composed-chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://evilcharts.com/docs/components/composed-chart",
    categories: ["charts"],
    proposedGroup: "charts",
  },
  {
    name: "animated-shiny-button",
    type: "registry:ui",
    title: "Animated Shiny Button",
    description:
      "Button with animated conic-gradient border, dot pattern, shimmer effect, and breathe animation.",
    files: [{ path: "components/ui/animated-shiny-button.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.eldoraui.site/docs/components/animated-shiny-button",
    categories: ["actions", "effects"],
    proposedGroup: "buttons",
  },
  {
    name: "browser",
    type: "registry:ui",
    title: "Browser",
    description:
      "Interactive browser simulator with tab management, address bar, navigation, bookmarks, history, and downloads.",
    files: [{ path: "components/ui/browser.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.eldoraui.site/docs/components/browser",
    registryDependencies: ["button", "badge", "card", "separator", "input"],
    categories: ["display"],
    proposedGroup: "display",
  },

  {
    name: "border-beam",
    type: "registry:ui",
    title: "Border Beam",
    description:
      "Animated border effect where a glowing beam travels around an element perimeter in a continuous loop.",
    files: [{ path: "components/ui/border-beam.tsx", type: "registry:ui" }],
    upstreamUrl: "https://magicui.design/docs/components/border-beam",
    categories: ["effects"],
    proposedGroup: "effects",
  },
  {
    name: "bottom-navigation",
    type: "registry:ui",
    title: "Bottom Navigation",
    description:
      "Mobile-first bottom navigation bar with icon and label items, fixed positioning, and safe-area support.",
    files: [{ path: "components/ui/bottom-navigation.tsx", type: "registry:ui" }],
    upstreamUrl: "https://shark.vini.one/docs/components/bottom-navigation",
    categories: ["navigation"],
    proposedGroup: "navigation",
  },
  {
    name: "commit-graph",
    type: "registry:ui",
    title: "Commit Graph",
    description:
      "Topological git graph with SVG rail lines showing branch forks, merges, and commit ancestry with interactive popovers.",
    files: [{ path: "components/ui/commit-graph.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.justinlevine.me/docs/components/commit-graph",
    categories: ["display", "data"],
    proposedGroup: "display",
  },
  {
    name: "marquee",
    type: "registry:ui",
    title: "Marquee",
    description:
      "Horizontal or vertical scrolling marquee animation with pause-on-hover, reverse direction, and configurable speed.",
    files: [{ path: "components/ui/marquee.tsx", type: "registry:ui" }],
    upstreamUrl: "https://magicui.design/docs/components/marquee",
    categories: ["effects"],
    proposedGroup: "effects",
  },
  {
    name: "reui-badge",
    type: "registry:ui",
    title: "ReUI Badge",
    description:
      "Enhanced badge with 20+ semantic variants (success, warning, info, destructive, light, outline), sizes, and radius.",
    files: [{ path: "components/ui/reui-badge.tsx", type: "registry:ui" }],
    upstreamUrl: "https://reui.io/components",
    categories: ["display"],
    proposedGroup: "display",
  },
  {
    name: "floating-panel",
    type: "registry:ui",
    title: "Floating Panel",
    description:
      "Non-modal floating window with drag, resize, minimize, maximize, and restore controls built on Ark UI.",
    registryDependencies: ["button", "scroll-area"],
    files: [{ path: "components/ui/floating-panel.tsx", type: "registry:ui" }],
    upstreamUrl: "https://shark.vini.one/docs/components/floating-panel",
    categories: ["overlay"],
    proposedGroup: "overlay",
  },
  {
    name: "signature-pad",
    type: "registry:ui",
    title: "Signature Pad",
    description:
      "Canvas-based hand-drawn signature capture with clear button, guide line, and image export via Ark UI.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/signature-pad.tsx", type: "registry:ui" }],
    upstreamUrl: "https://shark.vini.one/docs/components/signature-pad",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "download-trigger",
    type: "registry:ui",
    title: "Download Trigger",
    description:
      "Programmatic file download utility supporting string, Blob, File, and async data sources via Ark UI.",
    files: [{ path: "components/ui/download-trigger.tsx", type: "registry:ui" }],
    upstreamUrl: "https://shark.vini.one/docs/utilities/download-trigger",
    categories: ["actions"],
    proposedGroup: "actions",
  },
  {
    name: "liquid-metal-button",
    type: "registry:ui",
    title: "Liquid Metal Button",
    description:
      "WebGL shader-powered button with 3D metallic liquid animation, ripple effects, and text or icon view modes.",
    files: [{ path: "components/ui/liquid-metal-button.tsx", type: "registry:ui" }],
    upstreamUrl: "https://www.jolyui.dev/docs/components/buttons/liquid-metal-button",
    categories: ["buttons"],
    proposedGroup: "buttons",
  },
  {
    name: "snail-timer",
    type: "registry:ui",
    title: "Snail Timer",
    description:
      "Animated countdown timer with a snail character traversing the screen, dust trail, and configurable duration.",
    files: [
      { path: "components/ui/snail-timer.tsx", type: "registry:ui" },
      { path: "components/ui/snail-timer.css", type: "registry:ui" },
    ],
    upstreamUrl: "https://www.uicapsule.com",
    categories: ["feedback"],
    proposedGroup: "feedback",
  },
  {
    name: "creatable-combobox",
    type: "registry:ui",
    title: "Creatable Combobox",
    description:
      "Combobox extension with autocomplete and dynamic item creation, built on Base UI and project Combobox primitive.",
    registryDependencies: ["combobox"],
    files: [{ path: "components/ui/creatable-combobox.tsx", type: "registry:ui" }],
    upstreamUrl: "https://flowkit-ui.vzkiss.com/docs/components/creatable-combobox",
    categories: ["forms"],
    proposedGroup: "forms",
  },
  {
    name: "data-table-filter",
    type: "registry:ui",
    title: "Data Table Filter",
    description:
      "Linear-style data table filter bar with subject + operator + value pill chips. Library-agnostic, supports client and server filtering strategies.",
    files: [{ path: "components/ui/data-table-filter.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.bazza.dev/docs/data-table-filter",
    categories: ["data"],
    proposedGroup: "data",
  },
]);
