/**
 * Primitive registry. One entry per file in `src/components/ui/`.
 *
 * Edit by hand. The build script reads this and validates every name.
 * `registryDependencies` lists OTHER primitives a primitive composes
 * (for example, `alert-dialog` depends on `button`).
 *
 * Each item maps to `https://ui.shadcn.com/docs/components/<name>`.
 */
import { defineItems } from "@/lib/registry-schema";

export const items = defineItems([
  {
    name: "accordion",
    type: "registry:ui",
    title: "Accordion",
    description:
      "Vertically stacked set of interactive headings, each revealing a section of content.",
    files: [{ path: "components/ui/accordion.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/accordion",
    categories: ["disclosure"],
  },
  {
    name: "alert",
    type: "registry:ui",
    title: "Alert",
    description: "Callout for user attention with optional icon, title, description, and action.",
    files: [{ path: "components/ui/alert.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/alert",
    categories: ["feedback"],
  },
  {
    name: "alert-dialog",
    type: "registry:ui",
    title: "Alert Dialog",
    description:
      "Modal dialog that interrupts the user with critical content and expects a response.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/alert-dialog.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/alert-dialog",
    categories: ["overlay", "feedback"],
  },
  {
    name: "aspect-ratio",
    type: "registry:ui",
    title: "Aspect Ratio",
    description: "Constrains content to a specified ratio.",
    files: [{ path: "components/ui/aspect-ratio.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/aspect-ratio",
    categories: ["layout"],
  },
  {
    name: "avatar",
    type: "registry:ui",
    title: "Avatar",
    description: "Image element with a fallback, plus group, badge, and count subcomponents.",
    files: [{ path: "components/ui/avatar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/avatar",
    categories: ["display"],
  },
  {
    name: "badge",
    type: "registry:ui",
    title: "Badge",
    description:
      "Small label component for status, counts, and tags. Variants and asChild supported.",
    files: [{ path: "components/ui/badge.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/badge",
    categories: ["display"],
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    title: "Breadcrumb",
    description: "Hierarchical navigation showing the path to the current resource.",
    files: [{ path: "components/ui/breadcrumb.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/breadcrumb",
    categories: ["navigation"],
  },
  {
    name: "button",
    type: "registry:ui",
    title: "Button",
    description:
      "Primary action element. Variants: default, outline, secondary, ghost, destructive, link. Sizes: xs, sm, default, lg, icon, icon-xs, icon-sm, icon-lg.",
    files: [{ path: "components/ui/button.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/button",
    categories: ["actions", "forms"],
  },
  {
    name: "button-group",
    type: "registry:ui",
    title: "Button Group",
    description: "Container that groups related buttons with shared edges and consistent styling.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/button-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/button-group",
    categories: ["actions"],
  },
  {
    name: "calendar",
    type: "registry:ui",
    title: "Calendar",
    description:
      "Date picker calendar. Modes: single, range. Supports presets, time picker, week numbers, custom cell renderers.",
    files: [{ path: "components/ui/calendar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/calendar",
    categories: ["forms", "display"],
  },
  {
    name: "card",
    type: "registry:ui",
    title: "Card",
    description: "Surface with header, content, and footer slots. Size variants supported.",
    files: [{ path: "components/ui/card.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/card",
    categories: ["layout", "display"],
  },
  {
    name: "carousel",
    type: "registry:ui",
    title: "Carousel",
    description: "Slide-and-swipe carousel with motion built on Embla.",
    files: [{ path: "components/ui/carousel.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/carousel",
    categories: ["display"],
  },
  {
    name: "chart",
    type: "registry:ui",
    title: "Chart",
    description: "Recharts-backed chart primitives with shared tooltip, legend, config tokens.",
    files: [{ path: "components/ui/chart.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/chart",
    categories: ["display", "data-viz"],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    title: "Checkbox",
    description: "Toggle between checked, unchecked, indeterminate states.",
    files: [{ path: "components/ui/checkbox.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/checkbox",
    categories: ["forms"],
  },
  {
    name: "collapsible",
    type: "registry:ui",
    title: "Collapsible",
    description: "Interactive component that expands and collapses a panel.",
    files: [{ path: "components/ui/collapsible.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/collapsible",
    categories: ["disclosure"],
  },
  {
    name: "combobox",
    type: "registry:ui",
    title: "Combobox",
    description:
      "Autocomplete input with a list of suggestions. Supports multi-select, groups, custom items.",
    registryDependencies: ["popover", "command"],
    files: [{ path: "components/ui/combobox.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/combobox",
    categories: ["forms"],
  },
  {
    name: "command",
    type: "registry:ui",
    title: "Command",
    description: "Command palette for search and quick actions, with shortcuts and groups.",
    registryDependencies: ["dialog"],
    files: [{ path: "components/ui/command.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/command",
    categories: ["navigation", "search"],
  },
  {
    name: "context-menu",
    type: "registry:ui",
    title: "Context Menu",
    description: "Menu of actions triggered by a right click.",
    files: [{ path: "components/ui/context-menu.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/context-menu",
    categories: ["overlay", "menu"],
  },
  {
    name: "dialog",
    type: "registry:ui",
    title: "Dialog",
    description: "Window overlaid on the primary window, rendering content underneath inert.",
    files: [{ path: "components/ui/dialog.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/dialog",
    categories: ["overlay"],
  },
  {
    name: "drawer",
    type: "registry:ui",
    title: "Drawer",
    description: "Edge-anchored drawer for React with vaul.",
    files: [{ path: "components/ui/drawer.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/drawer",
    categories: ["overlay"],
  },
  {
    name: "dropdown-menu",
    type: "registry:ui",
    title: "Dropdown Menu",
    description:
      "Menu of actions or functions triggered by a button. Submenus, checkboxes, radio groups, shortcuts.",
    files: [{ path: "components/ui/dropdown-menu.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/dropdown-menu",
    categories: ["overlay", "menu"],
  },
  {
    name: "empty",
    type: "registry:ui",
    title: "Empty",
    description:
      "Empty-state component with media, header, title, description, content, action slots.",
    files: [{ path: "components/ui/empty.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/empty",
    categories: ["feedback", "display"],
  },
  {
    name: "field",
    type: "registry:ui",
    title: "Field",
    description: "Composable form field wrapper: label, control, description, error.",
    registryDependencies: ["label"],
    files: [{ path: "components/ui/field.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/field",
    categories: ["forms"],
  },
  {
    name: "hover-card",
    type: "registry:ui",
    title: "Hover Card",
    description: "Preview content available behind a link on hover (sighted users only).",
    files: [{ path: "components/ui/hover-card.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/hover-card",
    categories: ["overlay"],
  },
  {
    name: "input",
    type: "registry:ui",
    title: "Input",
    description: "Text input. Supports type variants, disabled, invalid (aria-invalid), file.",
    files: [{ path: "components/ui/input.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/input",
    categories: ["forms"],
  },
  {
    name: "input-group",
    type: "registry:ui",
    title: "Input Group",
    description: "Composed input layout with addons, buttons, and helper content.",
    registryDependencies: ["input"],
    files: [{ path: "components/ui/input-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/input-group",
    categories: ["forms"],
  },
  {
    name: "input-otp",
    type: "registry:ui",
    title: "Input OTP",
    description:
      "One-time password input with copy-paste, separators, patterns. ALWAYS controlled — never use defaultValue (library bug).",
    files: [{ path: "components/ui/input-otp.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/input-otp",
    categories: ["forms"],
    deviations: [
      "Must use controlled value/onChange. Library renders both value and defaultValue on hidden input when defaultValue is set, triggering React error.",
    ],
  },
  {
    name: "item",
    type: "registry:ui",
    title: "Item",
    description: "Versatile list/row component with media, title, description, and actions slots.",
    files: [{ path: "components/ui/item.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/item",
    categories: ["display", "layout"],
  },
  {
    name: "kbd",
    type: "registry:ui",
    title: "Kbd",
    description: "Display textual keyboard input. Group multiple keys with KbdGroup.",
    files: [{ path: "components/ui/kbd.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/kbd",
    categories: ["display"],
  },
  {
    name: "label",
    type: "registry:ui",
    title: "Label",
    description: "Accessible label associated with form controls.",
    files: [{ path: "components/ui/label.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/label",
    categories: ["forms"],
  },
  {
    name: "menubar",
    type: "registry:ui",
    title: "Menubar",
    description:
      "Persistent menu common in desktop apps. Submenus, checkboxes, radio groups, shortcuts.",
    files: [{ path: "components/ui/menubar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/menubar",
    categories: ["navigation", "menu"],
  },
  {
    name: "native-select",
    type: "registry:ui",
    title: "Native Select",
    description: "Styled native HTML <select> element with consistent design system integration.",
    files: [{ path: "components/ui/native-select.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/native-select",
    categories: ["forms"],
  },
  {
    name: "navigation-menu",
    type: "registry:ui",
    title: "Navigation Menu",
    description: "Collection of links with optional dropdown panels for site navigation.",
    files: [{ path: "components/ui/navigation-menu.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/navigation-menu",
    categories: ["navigation"],
  },
  {
    name: "pagination",
    type: "registry:ui",
    title: "Pagination",
    description: "Page navigation with previous, next, and numbered links.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/pagination.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/pagination",
    categories: ["navigation"],
  },
  {
    name: "popover",
    type: "registry:ui",
    title: "Popover",
    description: "Rich content in a portal triggered by a button.",
    files: [{ path: "components/ui/popover.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/popover",
    categories: ["overlay"],
  },
  {
    name: "progress",
    type: "registry:ui",
    title: "Progress",
    description: "Progress bar showing completion of a task.",
    files: [{ path: "components/ui/progress.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/progress",
    categories: ["feedback"],
  },
  {
    name: "radio-group",
    type: "registry:ui",
    title: "Radio Group",
    description: "Set of checkable radio buttons; only one selected at a time.",
    files: [{ path: "components/ui/radio-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/radio-group",
    categories: ["forms"],
  },
  {
    name: "resizable",
    type: "registry:ui",
    title: "Resizable",
    description: "Accessible resizable panel groups with keyboard support.",
    files: [{ path: "components/ui/resizable.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/resizable",
    categories: ["layout"],
  },
  {
    name: "scroll-area",
    type: "registry:ui",
    title: "Scroll Area",
    description: "Augmented native scroll with custom cross-browser styling.",
    files: [{ path: "components/ui/scroll-area.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/scroll-area",
    categories: ["layout"],
  },
  {
    name: "select",
    type: "registry:ui",
    title: "Select",
    description: "Listbox-style select with groups, scrollable lists, and triggers.",
    files: [{ path: "components/ui/select.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/select",
    categories: ["forms"],
  },
  {
    name: "separator",
    type: "registry:ui",
    title: "Separator",
    description: "Visual or semantic divider between content.",
    files: [{ path: "components/ui/separator.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/separator",
    categories: ["layout"],
  },
  {
    name: "sheet",
    type: "registry:ui",
    title: "Sheet",
    description: "Edge-anchored panel extending Dialog for complementary content.",
    registryDependencies: ["dialog"],
    files: [{ path: "components/ui/sheet.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/sheet",
    categories: ["overlay"],
  },
  {
    name: "sidebar",
    type: "registry:ui",
    title: "Sidebar",
    description:
      "Composable themeable sidebar with provider, header, footer, content, menu, trigger, rail, inset, and collapsible behaviors.",
    registryDependencies: ["button", "tooltip", "sheet"],
    files: [{ path: "components/ui/sidebar.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/sidebar",
    categories: ["layout", "navigation"],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    title: "Skeleton",
    description: "Loading-state placeholder.",
    files: [{ path: "components/ui/skeleton.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/skeleton",
    categories: ["feedback"],
  },
  {
    name: "slider",
    type: "registry:ui",
    title: "Slider",
    description: "Range input. Single thumb, multiple thumbs, vertical orientation supported.",
    files: [{ path: "components/ui/slider.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/slider",
    categories: ["forms"],
  },
  {
    name: "sonner",
    type: "registry:ui",
    title: "Sonner",
    description: "Toast notifications. Types: default, success, info, warning, error, promise.",
    files: [{ path: "components/ui/sonner.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/sonner",
    categories: ["feedback"],
  },
  {
    name: "spinner",
    type: "registry:ui",
    title: "Spinner",
    description: "Loading indicator. Compose with Button, Badge, Input Group, Empty.",
    files: [{ path: "components/ui/spinner.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/spinner",
    categories: ["feedback"],
  },
  {
    name: "switch",
    type: "registry:ui",
    title: "Switch",
    description: "Toggle control: checked / unchecked. Sized variants supported.",
    files: [{ path: "components/ui/switch.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/switch",
    categories: ["forms"],
  },
  {
    name: "table",
    type: "registry:ui",
    title: "Table",
    description: "Responsive table with header, body, footer, caption.",
    files: [{ path: "components/ui/table.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/table",
    categories: ["display", "data"],
  },
  {
    name: "tabs",
    type: "registry:ui",
    title: "Tabs",
    description: "Layered sections of content displayed one panel at a time.",
    files: [{ path: "components/ui/tabs.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/tabs",
    categories: ["navigation", "disclosure"],
  },
  {
    name: "textarea",
    type: "registry:ui",
    title: "Textarea",
    description: "Multi-line text input.",
    files: [{ path: "components/ui/textarea.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/textarea",
    categories: ["forms"],
  },
  {
    name: "toggle",
    type: "registry:ui",
    title: "Toggle",
    description: "Two-state button (on/off). Variants and sizes.",
    files: [{ path: "components/ui/toggle.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/toggle",
    categories: ["actions"],
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    title: "Toggle Group",
    description: "Set of two-state buttons. Single/multiple selection, vertical, spacing prop.",
    registryDependencies: ["toggle"],
    files: [{ path: "components/ui/toggle-group.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/toggle-group",
    categories: ["actions"],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    title: "Tooltip",
    description: "Floating popup on focus or hover with descriptive text.",
    files: [{ path: "components/ui/tooltip.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.shadcn.com/docs/components/tooltip",
    categories: ["overlay"],
  },
  {
    name: "noise-background",
    type: "registry:ui",
    title: "Noise Background",
    description:
      "Animated gradient background with noise texture overlay, spring physics, adjustable speed, and optional backdrop blur.",
    files: [{ path: "components/ui/noise-background.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.aceternity.com/components/noise-background",
    categories: ["display", "effects"],
    proposedGroup: "effects",
  },
  {
    name: "stateful-button",
    type: "registry:ui",
    title: "Stateful Button",
    description:
      "Action button with built-in loading spinner and success check animation sequence driven by motion/react.",
    registryDependencies: ["button"],
    files: [{ path: "components/ui/stateful-button.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.aceternity.com/components/stateful-button",
    categories: ["actions", "effects"],
    proposedGroup: "buttons",
  },
  {
    name: "multi-step-loader",
    type: "registry:ui",
    title: "Multi Step Loader",
    description:
      "Full-screen loading overlay that cycles through a list of steps with animated check marks and progress indicators.",
    files: [{ path: "components/ui/multi-step-loader.tsx", type: "registry:ui" }],
    upstreamUrl: "https://ui.aceternity.com/components/multi-step-loader",
    categories: ["feedback", "effects"],
    proposedGroup: "feedback",
  },
  {
    name: "separator-extended",
    type: "registry:ui",
    title: "Separator Extended",
    description:
      "Separator with variant styles: solid (default), dashed, dotted, and double. Supports horizontal and vertical orientation.",
    registryDependencies: ["separator"],
    files: [{ path: "components/ui/separator-extended.tsx", type: "registry:ui" }],
    upstreamUrl: "https://basecn.dev/docs/components/separator-extended",
    categories: ["layout"],
    proposedGroup: "layout",
  },
  {
    name: "card-styles",
    type: "registry:ui",
    title: "Card Styles",
    description:
      "Creative card style variants: retro shadow, line borders, hatched pattern, aurora glow, tilted layer, and stacked depth.",
    registryDependencies: ["card"],
    files: [{ path: "components/ui/card-styles.tsx", type: "registry:ui" }],
    upstreamUrl: "https://cardcn.dev/cards/basic-cards/",
    categories: ["display", "layout"],
    proposedGroup: "display",
  },
  {
    name: "autocomplete",
    type: "registry:ui",
    title: "Autocomplete",
    description:
      "Input that suggests options as you type. Inline autofill, auto-highlight, async search, groups, clear button, and trigger toggle.",
    registryDependencies: ["scroll-area"],
    files: [{ path: "components/ui/autocomplete.tsx", type: "registry:ui" }],
    upstreamUrl: "https://coss.com/ui/docs/components/autocomplete",
    categories: ["forms"],
    proposedGroup: "forms",
  },
]);
